// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/proto/structure.proto

package structurepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StructureService_GetUniversityByID_FullMethodName  = "/structure.StructureService/GetUniversityByID"
	StructureService_GetUniversityByINN_FullMethodName = "/structure.StructureService/GetUniversityByINN"
)

// StructureServiceClient is the client API for StructureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StructureService предоставляет методы для работы со структурой вузов
type StructureServiceClient interface {
	// GetUniversityByID получает вуз по ID
	GetUniversityByID(ctx context.Context, in *GetUniversityByIDRequest, opts ...grpc.CallOption) (*GetUniversityByIDResponse, error)
	// GetUniversityByINN получает вуз по ИНН
	GetUniversityByINN(ctx context.Context, in *GetUniversityByINNRequest, opts ...grpc.CallOption) (*GetUniversityByINNResponse, error)
}

type structureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStructureServiceClient(cc grpc.ClientConnInterface) StructureServiceClient {
	return &structureServiceClient{cc}
}

func (c *structureServiceClient) GetUniversityByID(ctx context.Context, in *GetUniversityByIDRequest, opts ...grpc.CallOption) (*GetUniversityByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUniversityByIDResponse)
	err := c.cc.Invoke(ctx, StructureService_GetUniversityByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *structureServiceClient) GetUniversityByINN(ctx context.Context, in *GetUniversityByINNRequest, opts ...grpc.CallOption) (*GetUniversityByINNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUniversityByINNResponse)
	err := c.cc.Invoke(ctx, StructureService_GetUniversityByINN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StructureServiceServer is the server API for StructureService service.
// All implementations must embed UnimplementedStructureServiceServer
// for forward compatibility.
//
// StructureService предоставляет методы для работы со структурой вузов
type StructureServiceServer interface {
	// GetUniversityByID получает вуз по ID
	GetUniversityByID(context.Context, *GetUniversityByIDRequest) (*GetUniversityByIDResponse, error)
	// GetUniversityByINN получает вуз по ИНН
	GetUniversityByINN(context.Context, *GetUniversityByINNRequest) (*GetUniversityByINNResponse, error)
	mustEmbedUnimplementedStructureServiceServer()
}

// UnimplementedStructureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStructureServiceServer struct{}

func (UnimplementedStructureServiceServer) GetUniversityByID(context.Context, *GetUniversityByIDRequest) (*GetUniversityByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniversityByID not implemented")
}
func (UnimplementedStructureServiceServer) GetUniversityByINN(context.Context, *GetUniversityByINNRequest) (*GetUniversityByINNResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniversityByINN not implemented")
}
func (UnimplementedStructureServiceServer) mustEmbedUnimplementedStructureServiceServer() {}
func (UnimplementedStructureServiceServer) testEmbeddedByValue()                          {}

// UnsafeStructureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StructureServiceServer will
// result in compilation errors.
type UnsafeStructureServiceServer interface {
	mustEmbedUnimplementedStructureServiceServer()
}

func RegisterStructureServiceServer(s grpc.ServiceRegistrar, srv StructureServiceServer) {
	// If the following call panics, it indicates UnimplementedStructureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StructureService_ServiceDesc, srv)
}

func _StructureService_GetUniversityByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUniversityByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StructureServiceServer).GetUniversityByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StructureService_GetUniversityByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StructureServiceServer).GetUniversityByID(ctx, req.(*GetUniversityByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StructureService_GetUniversityByINN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUniversityByINNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StructureServiceServer).GetUniversityByINN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StructureService_GetUniversityByINN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StructureServiceServer).GetUniversityByINN(ctx, req.(*GetUniversityByINNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StructureService_ServiceDesc is the grpc.ServiceDesc for StructureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StructureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "structure.StructureService",
	HandlerType: (*StructureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUniversityByID",
			Handler:    _StructureService_GetUniversityByID_Handler,
		},
		{
			MethodName: "GetUniversityByINN",
			Handler:    _StructureService_GetUniversityByINN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/structure.proto",
}
