// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/structure.proto

package structurepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// University list messages
type GetAllUniversitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUniversitiesRequest) Reset() {
	*x = GetAllUniversitiesRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUniversitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUniversitiesRequest) ProtoMessage() {}

func (x *GetAllUniversitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUniversitiesRequest.ProtoReflect.Descriptor instead.
func (*GetAllUniversitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllUniversitiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllUniversitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllUniversitiesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetAllUniversitiesRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type GetAllUniversitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Universities  []*University          `protobuf:"bytes,1,rep,name=universities,proto3" json:"universities,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUniversitiesResponse) Reset() {
	*x = GetAllUniversitiesResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUniversitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUniversitiesResponse) ProtoMessage() {}

func (x *GetAllUniversitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUniversitiesResponse.ProtoReflect.Descriptor instead.
func (*GetAllUniversitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllUniversitiesResponse) GetUniversities() []*University {
	if x != nil {
		return x.Universities
	}
	return nil
}

func (x *GetAllUniversitiesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllUniversitiesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllUniversitiesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllUniversitiesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateUniversityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inn           string                 `protobuf:"bytes,2,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp           string                 `protobuf:"bytes,3,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Foiv          string                 `protobuf:"bytes,4,opt,name=foiv,proto3" json:"foiv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUniversityRequest) Reset() {
	*x = CreateUniversityRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUniversityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUniversityRequest) ProtoMessage() {}

func (x *CreateUniversityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUniversityRequest.ProtoReflect.Descriptor instead.
func (*CreateUniversityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUniversityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUniversityRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *CreateUniversityRequest) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *CreateUniversityRequest) GetFoiv() string {
	if x != nil {
		return x.Foiv
	}
	return ""
}

type CreateUniversityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUniversityResponse) Reset() {
	*x = CreateUniversityResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUniversityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUniversityResponse) ProtoMessage() {}

func (x *CreateUniversityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUniversityResponse.ProtoReflect.Descriptor instead.
func (*CreateUniversityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUniversityResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *CreateUniversityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUniversityByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByIDRequest) Reset() {
	*x = GetUniversityByIDRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByIDRequest) ProtoMessage() {}

func (x *GetUniversityByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{4}
}

func (x *GetUniversityByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUniversityByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByIDResponse) Reset() {
	*x = GetUniversityByIDResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByIDResponse) ProtoMessage() {}

func (x *GetUniversityByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{5}
}

func (x *GetUniversityByIDResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *GetUniversityByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUniversityByINNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inn           string                 `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByINNRequest) Reset() {
	*x = GetUniversityByINNRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByINNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByINNRequest) ProtoMessage() {}

func (x *GetUniversityByINNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByINNRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityByINNRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{6}
}

func (x *GetUniversityByINNRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type GetUniversityByINNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByINNResponse) Reset() {
	*x = GetUniversityByINNResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByINNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByINNResponse) ProtoMessage() {}

func (x *GetUniversityByINNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByINNResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityByINNResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{7}
}

func (x *GetUniversityByINNResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *GetUniversityByINNResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUniversityStructureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniversityId  int64                  `protobuf:"varint,1,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityStructureRequest) Reset() {
	*x = GetUniversityStructureRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityStructureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityStructureRequest) ProtoMessage() {}

func (x *GetUniversityStructureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityStructureRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityStructureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{8}
}

func (x *GetUniversityStructureRequest) GetUniversityId() int64 {
	if x != nil {
		return x.UniversityId
	}
	return 0
}

type GetUniversityStructureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Structure     *UniversityStructure   `protobuf:"bytes,1,opt,name=structure,proto3" json:"structure,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityStructureResponse) Reset() {
	*x = GetUniversityStructureResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityStructureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityStructureResponse) ProtoMessage() {}

func (x *GetUniversityStructureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityStructureResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityStructureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{9}
}

func (x *GetUniversityStructureResponse) GetStructure() *UniversityStructure {
	if x != nil {
		return x.Structure
	}
	return nil
}

func (x *GetUniversityStructureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateUniversityNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniversityId  int64                  `protobuf:"varint,1,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUniversityNameRequest) Reset() {
	*x = UpdateUniversityNameRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUniversityNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUniversityNameRequest) ProtoMessage() {}

func (x *UpdateUniversityNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUniversityNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUniversityNameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUniversityNameRequest) GetUniversityId() int64 {
	if x != nil {
		return x.UniversityId
	}
	return 0
}

func (x *UpdateUniversityNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateUniversityNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUniversityNameResponse) Reset() {
	*x = UpdateUniversityNameResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUniversityNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUniversityNameResponse) ProtoMessage() {}

func (x *UpdateUniversityNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUniversityNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateUniversityNameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUniversityNameResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *UpdateUniversityNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateOrGetUniversityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inn           string                 `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp           string                 `protobuf:"bytes,2,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Foiv          string                 `protobuf:"bytes,4,opt,name=foiv,proto3" json:"foiv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrGetUniversityRequest) Reset() {
	*x = CreateOrGetUniversityRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrGetUniversityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrGetUniversityRequest) ProtoMessage() {}

func (x *CreateOrGetUniversityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrGetUniversityRequest.ProtoReflect.Descriptor instead.
func (*CreateOrGetUniversityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{12}
}

func (x *CreateOrGetUniversityRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *CreateOrGetUniversityRequest) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *CreateOrGetUniversityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrGetUniversityRequest) GetFoiv() string {
	if x != nil {
		return x.Foiv
	}
	return ""
}

type CreateOrGetUniversityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrGetUniversityResponse) Reset() {
	*x = CreateOrGetUniversityResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrGetUniversityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrGetUniversityResponse) ProtoMessage() {}

func (x *CreateOrGetUniversityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrGetUniversityResponse.ProtoReflect.Descriptor instead.
func (*CreateOrGetUniversityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{13}
}

func (x *CreateOrGetUniversityResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *CreateOrGetUniversityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type University struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Inn           string                 `protobuf:"bytes,3,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp           string                 `protobuf:"bytes,4,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Foiv          string                 `protobuf:"bytes,5,opt,name=foiv,proto3" json:"foiv,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *University) Reset() {
	*x = University{}
	mi := &file_api_proto_structure_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *University) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*University) ProtoMessage() {}

func (x *University) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use University.ProtoReflect.Descriptor instead.
func (*University) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{14}
}

func (x *University) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *University) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *University) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *University) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *University) GetFoiv() string {
	if x != nil {
		return x.Foiv
	}
	return ""
}

func (x *University) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *University) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UniversityStructure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Branches      []*Branch              `protobuf:"bytes,2,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniversityStructure) Reset() {
	*x = UniversityStructure{}
	mi := &file_api_proto_structure_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniversityStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversityStructure) ProtoMessage() {}

func (x *UniversityStructure) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversityStructure.ProtoReflect.Descriptor instead.
func (*UniversityStructure) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{15}
}

func (x *UniversityStructure) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *UniversityStructure) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UniversityId  int64                  `protobuf:"varint,3,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	Faculties     []*Faculty             `protobuf:"bytes,4,rep,name=faculties,proto3" json:"faculties,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_api_proto_structure_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{16}
}

func (x *Branch) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetUniversityId() int64 {
	if x != nil {
		return x.UniversityId
	}
	return 0
}

func (x *Branch) GetFaculties() []*Faculty {
	if x != nil {
		return x.Faculties
	}
	return nil
}

func (x *Branch) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Branch) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Faculty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BranchId      int64                  `protobuf:"varint,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Groups        []*Group               `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Faculty) Reset() {
	*x = Faculty{}
	mi := &file_api_proto_structure_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Faculty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Faculty) ProtoMessage() {}

func (x *Faculty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Faculty.ProtoReflect.Descriptor instead.
func (*Faculty) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{17}
}

func (x *Faculty) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Faculty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Faculty) GetBranchId() int64 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

func (x *Faculty) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Faculty) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Faculty) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Course        int32                  `protobuf:"varint,3,opt,name=course,proto3" json:"course,omitempty"`
	FacultyId     int64                  `protobuf:"varint,4,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	ChatId        *int64                 `protobuf:"varint,5,opt,name=chat_id,json=chatId,proto3,oneof" json:"chat_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_api_proto_structure_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{18}
}

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Group) GetCourse() int32 {
	if x != nil {
		return x.Course
	}
	return 0
}

func (x *Group) GetFacultyId() int64 {
	if x != nil {
		return x.FacultyId
	}
	return 0
}

func (x *Group) GetChatId() int64 {
	if x != nil && x.ChatId != nil {
		return *x.ChatId
	}
	return 0
}

func (x *Group) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Group) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Structure creation messages
type CreateStructureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inn           string                 `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp           string                 `protobuf:"bytes,2,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Foiv          string                 `protobuf:"bytes,3,opt,name=foiv,proto3" json:"foiv,omitempty"`
	OrgName       string                 `protobuf:"bytes,4,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	BranchName    string                 `protobuf:"bytes,5,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	FacultyName   string                 `protobuf:"bytes,6,opt,name=faculty_name,json=facultyName,proto3" json:"faculty_name,omitempty"`
	Course        int32                  `protobuf:"varint,7,opt,name=course,proto3" json:"course,omitempty"`
	GroupNumber   string                 `protobuf:"bytes,8,opt,name=group_number,json=groupNumber,proto3" json:"group_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStructureRequest) Reset() {
	*x = CreateStructureRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStructureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStructureRequest) ProtoMessage() {}

func (x *CreateStructureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStructureRequest.ProtoReflect.Descriptor instead.
func (*CreateStructureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{19}
}

func (x *CreateStructureRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *CreateStructureRequest) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *CreateStructureRequest) GetFoiv() string {
	if x != nil {
		return x.Foiv
	}
	return ""
}

func (x *CreateStructureRequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *CreateStructureRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *CreateStructureRequest) GetFacultyName() string {
	if x != nil {
		return x.FacultyName
	}
	return ""
}

func (x *CreateStructureRequest) GetCourse() int32 {
	if x != nil {
		return x.Course
	}
	return 0
}

func (x *CreateStructureRequest) GetGroupNumber() string {
	if x != nil {
		return x.GroupNumber
	}
	return ""
}

type CreateStructureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniversityId  int64                  `protobuf:"varint,1,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	BranchId      *int64                 `protobuf:"varint,2,opt,name=branch_id,json=branchId,proto3,oneof" json:"branch_id,omitempty"`
	FacultyId     *int64                 `protobuf:"varint,3,opt,name=faculty_id,json=facultyId,proto3,oneof" json:"faculty_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStructureResponse) Reset() {
	*x = CreateStructureResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStructureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStructureResponse) ProtoMessage() {}

func (x *CreateStructureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStructureResponse.ProtoReflect.Descriptor instead.
func (*CreateStructureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{20}
}

func (x *CreateStructureResponse) GetUniversityId() int64 {
	if x != nil {
		return x.UniversityId
	}
	return 0
}

func (x *CreateStructureResponse) GetBranchId() int64 {
	if x != nil && x.BranchId != nil {
		return *x.BranchId
	}
	return 0
}

func (x *CreateStructureResponse) GetFacultyId() int64 {
	if x != nil && x.FacultyId != nil {
		return *x.FacultyId
	}
	return 0
}

func (x *CreateStructureResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateStructureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Import messages
type ImportExcelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportExcelRequest) Reset() {
	*x = ImportExcelRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportExcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportExcelRequest) ProtoMessage() {}

func (x *ImportExcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportExcelRequest.ProtoReflect.Descriptor instead.
func (*ImportExcelRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{21}
}

func (x *ImportExcelRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *ImportExcelRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ImportExcelResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessedRows  int32                  `protobuf:"varint,1,opt,name=processed_rows,json=processedRows,proto3" json:"processed_rows,omitempty"`
	SuccessfulRows int32                  `protobuf:"varint,2,opt,name=successful_rows,json=successfulRows,proto3" json:"successful_rows,omitempty"`
	FailedRows     int32                  `protobuf:"varint,3,opt,name=failed_rows,json=failedRows,proto3" json:"failed_rows,omitempty"`
	Errors         []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportExcelResponse) Reset() {
	*x = ImportExcelResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportExcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportExcelResponse) ProtoMessage() {}

func (x *ImportExcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportExcelResponse.ProtoReflect.Descriptor instead.
func (*ImportExcelResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{22}
}

func (x *ImportExcelResponse) GetProcessedRows() int32 {
	if x != nil {
		return x.ProcessedRows
	}
	return 0
}

func (x *ImportExcelResponse) GetSuccessfulRows() int32 {
	if x != nil {
		return x.SuccessfulRows
	}
	return 0
}

func (x *ImportExcelResponse) GetFailedRows() int32 {
	if x != nil {
		return x.FailedRows
	}
	return 0
}

func (x *ImportExcelResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ImportExcelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Update name messages
type UpdateBranchNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchId      int64                  `protobuf:"varint,1,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBranchNameRequest) Reset() {
	*x = UpdateBranchNameRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBranchNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBranchNameRequest) ProtoMessage() {}

func (x *UpdateBranchNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBranchNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateBranchNameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateBranchNameRequest) GetBranchId() int64 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

func (x *UpdateBranchNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateBranchNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBranchNameResponse) Reset() {
	*x = UpdateBranchNameResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBranchNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBranchNameResponse) ProtoMessage() {}

func (x *UpdateBranchNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBranchNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateBranchNameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateBranchNameResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

func (x *UpdateBranchNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateFacultyNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FacultyId     int64                  `protobuf:"varint,1,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacultyNameRequest) Reset() {
	*x = UpdateFacultyNameRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacultyNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacultyNameRequest) ProtoMessage() {}

func (x *UpdateFacultyNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacultyNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateFacultyNameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateFacultyNameRequest) GetFacultyId() int64 {
	if x != nil {
		return x.FacultyId
	}
	return 0
}

func (x *UpdateFacultyNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateFacultyNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faculty       *Faculty               `protobuf:"bytes,1,opt,name=faculty,proto3" json:"faculty,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacultyNameResponse) Reset() {
	*x = UpdateFacultyNameResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacultyNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacultyNameResponse) ProtoMessage() {}

func (x *UpdateFacultyNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacultyNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateFacultyNameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateFacultyNameResponse) GetFaculty() *Faculty {
	if x != nil {
		return x.Faculty
	}
	return nil
}

func (x *UpdateFacultyNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateGroupNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupNameRequest) Reset() {
	*x = UpdateGroupNameRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupNameRequest) ProtoMessage() {}

func (x *UpdateGroupNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupNameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateGroupNameRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupNameRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type UpdateGroupNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupNameResponse) Reset() {
	*x = UpdateGroupNameResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupNameResponse) ProtoMessage() {}

func (x *UpdateGroupNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupNameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateGroupNameResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *UpdateGroupNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LinkGroupToChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkGroupToChatRequest) Reset() {
	*x = LinkGroupToChatRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkGroupToChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkGroupToChatRequest) ProtoMessage() {}

func (x *LinkGroupToChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkGroupToChatRequest.ProtoReflect.Descriptor instead.
func (*LinkGroupToChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{29}
}

func (x *LinkGroupToChatRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *LinkGroupToChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type LinkGroupToChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkGroupToChatResponse) Reset() {
	*x = LinkGroupToChatResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkGroupToChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkGroupToChatResponse) ProtoMessage() {}

func (x *LinkGroupToChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkGroupToChatResponse.ProtoReflect.Descriptor instead.
func (*LinkGroupToChatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{30}
}

func (x *LinkGroupToChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LinkGroupToChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Department manager messages
type GetAllDepartmentManagersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDepartmentManagersRequest) Reset() {
	*x = GetAllDepartmentManagersRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDepartmentManagersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDepartmentManagersRequest) ProtoMessage() {}

func (x *GetAllDepartmentManagersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDepartmentManagersRequest.ProtoReflect.Descriptor instead.
func (*GetAllDepartmentManagersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{31}
}

func (x *GetAllDepartmentManagersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllDepartmentManagersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAllDepartmentManagersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Managers      []*DepartmentManager   `protobuf:"bytes,1,rep,name=managers,proto3" json:"managers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDepartmentManagersResponse) Reset() {
	*x = GetAllDepartmentManagersResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDepartmentManagersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDepartmentManagersResponse) ProtoMessage() {}

func (x *GetAllDepartmentManagersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDepartmentManagersResponse.ProtoReflect.Descriptor instead.
func (*GetAllDepartmentManagersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{32}
}

func (x *GetAllDepartmentManagersResponse) GetManagers() []*DepartmentManager {
	if x != nil {
		return x.Managers
	}
	return nil
}

func (x *GetAllDepartmentManagersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllDepartmentManagersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllDepartmentManagersResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllDepartmentManagersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateDepartmentManagerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DepartmentId  int64                  `protobuf:"varint,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentManagerRequest) Reset() {
	*x = CreateDepartmentManagerRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentManagerRequest) ProtoMessage() {}

func (x *CreateDepartmentManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentManagerRequest.ProtoReflect.Descriptor instead.
func (*CreateDepartmentManagerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{33}
}

func (x *CreateDepartmentManagerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateDepartmentManagerRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type CreateDepartmentManagerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manager       *DepartmentManager     `protobuf:"bytes,1,opt,name=manager,proto3" json:"manager,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentManagerResponse) Reset() {
	*x = CreateDepartmentManagerResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentManagerResponse) ProtoMessage() {}

func (x *CreateDepartmentManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentManagerResponse.ProtoReflect.Descriptor instead.
func (*CreateDepartmentManagerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{34}
}

func (x *CreateDepartmentManagerResponse) GetManager() *DepartmentManager {
	if x != nil {
		return x.Manager
	}
	return nil
}

func (x *CreateDepartmentManagerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemoveDepartmentManagerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     int64                  `protobuf:"varint,1,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDepartmentManagerRequest) Reset() {
	*x = RemoveDepartmentManagerRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDepartmentManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDepartmentManagerRequest) ProtoMessage() {}

func (x *RemoveDepartmentManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDepartmentManagerRequest.ProtoReflect.Descriptor instead.
func (*RemoveDepartmentManagerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{35}
}

func (x *RemoveDepartmentManagerRequest) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

type RemoveDepartmentManagerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDepartmentManagerResponse) Reset() {
	*x = RemoveDepartmentManagerResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDepartmentManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDepartmentManagerResponse) ProtoMessage() {}

func (x *RemoveDepartmentManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDepartmentManagerResponse.ProtoReflect.Descriptor instead.
func (*RemoveDepartmentManagerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{36}
}

func (x *RemoveDepartmentManagerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveDepartmentManagerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DepartmentManager struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DepartmentId  int64                  `protobuf:"varint,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentManager) Reset() {
	*x = DepartmentManager{}
	mi := &file_api_proto_structure_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentManager) ProtoMessage() {}

func (x *DepartmentManager) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentManager.ProtoReflect.Descriptor instead.
func (*DepartmentManager) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{37}
}

func (x *DepartmentManager) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepartmentManager) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DepartmentManager) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *DepartmentManager) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Health messages
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{38}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{39}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_structure_proto protoreflect.FileDescriptor

const file_api_proto_structure_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/structure.proto\x12\tstructure\"}\n" +
	"\x19GetAllUniversitiesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\"\xad\x01\n" +
	"\x1aGetAllUniversitiesResponse\x129\n" +
	"\funiversities\x18\x01 \x03(\v2\x15.structure.UniversityR\funiversities\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"e\n" +
	"\x17CreateUniversityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03inn\x18\x02 \x01(\tR\x03inn\x12\x10\n" +
	"\x03kpp\x18\x03 \x01(\tR\x03kpp\x12\x12\n" +
	"\x04foiv\x18\x04 \x01(\tR\x04foiv\"g\n" +
	"\x18CreateUniversityResponse\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"*\n" +
	"\x18GetUniversityByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"h\n" +
	"\x19GetUniversityByIDResponse\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x19GetUniversityByINNRequest\x12\x10\n" +
	"\x03inn\x18\x01 \x01(\tR\x03inn\"i\n" +
	"\x1aGetUniversityByINNResponse\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"D\n" +
	"\x1dGetUniversityStructureRequest\x12#\n" +
	"\runiversity_id\x18\x01 \x01(\x03R\funiversityId\"t\n" +
	"\x1eGetUniversityStructureResponse\x12<\n" +
	"\tstructure\x18\x01 \x01(\v2\x1e.structure.UniversityStructureR\tstructure\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\x1bUpdateUniversityNameRequest\x12#\n" +
	"\runiversity_id\x18\x01 \x01(\x03R\funiversityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"k\n" +
	"\x1cUpdateUniversityNameResponse\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"j\n" +
	"\x1cCreateOrGetUniversityRequest\x12\x10\n" +
	"\x03inn\x18\x01 \x01(\tR\x03inn\x12\x10\n" +
	"\x03kpp\x18\x02 \x01(\tR\x03kpp\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04foiv\x18\x04 \x01(\tR\x04foiv\"l\n" +
	"\x1dCreateOrGetUniversityResponse\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa6\x01\n" +
	"\n" +
	"University\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03inn\x18\x03 \x01(\tR\x03inn\x12\x10\n" +
	"\x03kpp\x18\x04 \x01(\tR\x03kpp\x12\x12\n" +
	"\x04foiv\x18\x05 \x01(\tR\x04foiv\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"{\n" +
	"\x13UniversityStructure\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12-\n" +
	"\bbranches\x18\x02 \x03(\v2\x11.structure.BranchR\bbranches\"\xc1\x01\n" +
	"\x06Branch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\runiversity_id\x18\x03 \x01(\x03R\funiversityId\x120\n" +
	"\tfaculties\x18\x04 \x03(\v2\x12.structure.FacultyR\tfaculties\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xb2\x01\n" +
	"\aFaculty\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tbranch_id\x18\x03 \x01(\x03R\bbranchId\x12(\n" +
	"\x06groups\x18\x04 \x03(\v2\x10.structure.GroupR\x06groups\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xce\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x16\n" +
	"\x06course\x18\x03 \x01(\x05R\x06course\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x04 \x01(\x03R\tfacultyId\x12\x1c\n" +
	"\achat_id\x18\x05 \x01(\x03H\x00R\x06chatId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAtB\n" +
	"\n" +
	"\b_chat_id\"\xea\x01\n" +
	"\x16CreateStructureRequest\x12\x10\n" +
	"\x03inn\x18\x01 \x01(\tR\x03inn\x12\x10\n" +
	"\x03kpp\x18\x02 \x01(\tR\x03kpp\x12\x12\n" +
	"\x04foiv\x18\x03 \x01(\tR\x04foiv\x12\x19\n" +
	"\borg_name\x18\x04 \x01(\tR\aorgName\x12\x1f\n" +
	"\vbranch_name\x18\x05 \x01(\tR\n" +
	"branchName\x12!\n" +
	"\ffaculty_name\x18\x06 \x01(\tR\vfacultyName\x12\x16\n" +
	"\x06course\x18\a \x01(\x05R\x06course\x12!\n" +
	"\fgroup_number\x18\b \x01(\tR\vgroupNumber\"\xd2\x01\n" +
	"\x17CreateStructureResponse\x12#\n" +
	"\runiversity_id\x18\x01 \x01(\x03R\funiversityId\x12 \n" +
	"\tbranch_id\x18\x02 \x01(\x03H\x00R\bbranchId\x88\x01\x01\x12\"\n" +
	"\n" +
	"faculty_id\x18\x03 \x01(\x03H\x01R\tfacultyId\x88\x01\x01\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\x03R\agroupId\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorB\f\n" +
	"\n" +
	"_branch_idB\r\n" +
	"\v_faculty_id\"M\n" +
	"\x12ImportExcelRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"\xb4\x01\n" +
	"\x13ImportExcelResponse\x12%\n" +
	"\x0eprocessed_rows\x18\x01 \x01(\x05R\rprocessedRows\x12'\n" +
	"\x0fsuccessful_rows\x18\x02 \x01(\x05R\x0esuccessfulRows\x12\x1f\n" +
	"\vfailed_rows\x18\x03 \x01(\x05R\n" +
	"failedRows\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"J\n" +
	"\x17UpdateBranchNameRequest\x12\x1b\n" +
	"\tbranch_id\x18\x01 \x01(\x03R\bbranchId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"[\n" +
	"\x18UpdateBranchNameResponse\x12)\n" +
	"\x06branch\x18\x01 \x01(\v2\x11.structure.BranchR\x06branch\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"M\n" +
	"\x18UpdateFacultyNameRequest\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x01 \x01(\x03R\tfacultyId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"_\n" +
	"\x19UpdateFacultyNameResponse\x12,\n" +
	"\afaculty\x18\x01 \x01(\v2\x12.structure.FacultyR\afaculty\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"K\n" +
	"\x16UpdateGroupNameRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\"W\n" +
	"\x17UpdateGroupNameResponse\x12&\n" +
	"\x05group\x18\x01 \x01(\v2\x10.structure.GroupR\x05group\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"L\n" +
	"\x16LinkGroupToChatRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\"I\n" +
	"\x17LinkGroupToChatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"K\n" +
	"\x1fGetAllDepartmentManagersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xb2\x01\n" +
	" GetAllDepartmentManagersResponse\x128\n" +
	"\bmanagers\x18\x01 \x03(\v2\x1c.structure.DepartmentManagerR\bmanagers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"^\n" +
	"\x1eCreateDepartmentManagerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\x03R\fdepartmentId\"o\n" +
	"\x1fCreateDepartmentManagerResponse\x126\n" +
	"\amanager\x18\x01 \x01(\v2\x1c.structure.DepartmentManagerR\amanager\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"?\n" +
	"\x1eRemoveDepartmentManagerRequest\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x01 \x01(\x03R\tmanagerId\"Q\n" +
	"\x1fRemoveDepartmentManagerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x80\x01\n" +
	"\x11DepartmentManager\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\x03R\fdepartmentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x8a\r\n" +
	"\x10StructureService\x12a\n" +
	"\x12GetAllUniversities\x12$.structure.GetAllUniversitiesRequest\x1a%.structure.GetAllUniversitiesResponse\x12[\n" +
	"\x10CreateUniversity\x12\".structure.CreateUniversityRequest\x1a#.structure.CreateUniversityResponse\x12^\n" +
	"\x11GetUniversityByID\x12#.structure.GetUniversityByIDRequest\x1a$.structure.GetUniversityByIDResponse\x12a\n" +
	"\x12GetUniversityByINN\x12$.structure.GetUniversityByINNRequest\x1a%.structure.GetUniversityByINNResponse\x12m\n" +
	"\x16GetUniversityStructure\x12(.structure.GetUniversityStructureRequest\x1a).structure.GetUniversityStructureResponse\x12g\n" +
	"\x14UpdateUniversityName\x12&.structure.UpdateUniversityNameRequest\x1a'.structure.UpdateUniversityNameResponse\x12j\n" +
	"\x15CreateOrGetUniversity\x12'.structure.CreateOrGetUniversityRequest\x1a(.structure.CreateOrGetUniversityResponse\x12X\n" +
	"\x0fCreateStructure\x12!.structure.CreateStructureRequest\x1a\".structure.CreateStructureResponse\x12L\n" +
	"\vImportExcel\x12\x1d.structure.ImportExcelRequest\x1a\x1e.structure.ImportExcelResponse\x12[\n" +
	"\x10UpdateBranchName\x12\".structure.UpdateBranchNameRequest\x1a#.structure.UpdateBranchNameResponse\x12^\n" +
	"\x11UpdateFacultyName\x12#.structure.UpdateFacultyNameRequest\x1a$.structure.UpdateFacultyNameResponse\x12X\n" +
	"\x0fUpdateGroupName\x12!.structure.UpdateGroupNameRequest\x1a\".structure.UpdateGroupNameResponse\x12X\n" +
	"\x0fLinkGroupToChat\x12!.structure.LinkGroupToChatRequest\x1a\".structure.LinkGroupToChatResponse\x12s\n" +
	"\x18GetAllDepartmentManagers\x12*.structure.GetAllDepartmentManagersRequest\x1a+.structure.GetAllDepartmentManagersResponse\x12p\n" +
	"\x17CreateDepartmentManager\x12).structure.CreateDepartmentManagerRequest\x1a*.structure.CreateDepartmentManagerResponse\x12p\n" +
	"\x17RemoveDepartmentManager\x12).structure.RemoveDepartmentManagerRequest\x1a*.structure.RemoveDepartmentManagerResponse\x12=\n" +
	"\x06Health\x12\x18.structure.HealthRequest\x1a\x19.structure.HealthResponseB)Z'structure-service/api/proto;structurepbb\x06proto3"

var (
	file_api_proto_structure_proto_rawDescOnce sync.Once
	file_api_proto_structure_proto_rawDescData []byte
)

func file_api_proto_structure_proto_rawDescGZIP() []byte {
	file_api_proto_structure_proto_rawDescOnce.Do(func() {
		file_api_proto_structure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_structure_proto_rawDesc), len(file_api_proto_structure_proto_rawDesc)))
	})
	return file_api_proto_structure_proto_rawDescData
}

var file_api_proto_structure_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_api_proto_structure_proto_goTypes = []any{
	(*GetAllUniversitiesRequest)(nil),        // 0: structure.GetAllUniversitiesRequest
	(*GetAllUniversitiesResponse)(nil),       // 1: structure.GetAllUniversitiesResponse
	(*CreateUniversityRequest)(nil),          // 2: structure.CreateUniversityRequest
	(*CreateUniversityResponse)(nil),         // 3: structure.CreateUniversityResponse
	(*GetUniversityByIDRequest)(nil),         // 4: structure.GetUniversityByIDRequest
	(*GetUniversityByIDResponse)(nil),        // 5: structure.GetUniversityByIDResponse
	(*GetUniversityByINNRequest)(nil),        // 6: structure.GetUniversityByINNRequest
	(*GetUniversityByINNResponse)(nil),       // 7: structure.GetUniversityByINNResponse
	(*GetUniversityStructureRequest)(nil),    // 8: structure.GetUniversityStructureRequest
	(*GetUniversityStructureResponse)(nil),   // 9: structure.GetUniversityStructureResponse
	(*UpdateUniversityNameRequest)(nil),      // 10: structure.UpdateUniversityNameRequest
	(*UpdateUniversityNameResponse)(nil),     // 11: structure.UpdateUniversityNameResponse
	(*CreateOrGetUniversityRequest)(nil),     // 12: structure.CreateOrGetUniversityRequest
	(*CreateOrGetUniversityResponse)(nil),    // 13: structure.CreateOrGetUniversityResponse
	(*University)(nil),                       // 14: structure.University
	(*UniversityStructure)(nil),              // 15: structure.UniversityStructure
	(*Branch)(nil),                           // 16: structure.Branch
	(*Faculty)(nil),                          // 17: structure.Faculty
	(*Group)(nil),                            // 18: structure.Group
	(*CreateStructureRequest)(nil),           // 19: structure.CreateStructureRequest
	(*CreateStructureResponse)(nil),          // 20: structure.CreateStructureResponse
	(*ImportExcelRequest)(nil),               // 21: structure.ImportExcelRequest
	(*ImportExcelResponse)(nil),              // 22: structure.ImportExcelResponse
	(*UpdateBranchNameRequest)(nil),          // 23: structure.UpdateBranchNameRequest
	(*UpdateBranchNameResponse)(nil),         // 24: structure.UpdateBranchNameResponse
	(*UpdateFacultyNameRequest)(nil),         // 25: structure.UpdateFacultyNameRequest
	(*UpdateFacultyNameResponse)(nil),        // 26: structure.UpdateFacultyNameResponse
	(*UpdateGroupNameRequest)(nil),           // 27: structure.UpdateGroupNameRequest
	(*UpdateGroupNameResponse)(nil),          // 28: structure.UpdateGroupNameResponse
	(*LinkGroupToChatRequest)(nil),           // 29: structure.LinkGroupToChatRequest
	(*LinkGroupToChatResponse)(nil),          // 30: structure.LinkGroupToChatResponse
	(*GetAllDepartmentManagersRequest)(nil),  // 31: structure.GetAllDepartmentManagersRequest
	(*GetAllDepartmentManagersResponse)(nil), // 32: structure.GetAllDepartmentManagersResponse
	(*CreateDepartmentManagerRequest)(nil),   // 33: structure.CreateDepartmentManagerRequest
	(*CreateDepartmentManagerResponse)(nil),  // 34: structure.CreateDepartmentManagerResponse
	(*RemoveDepartmentManagerRequest)(nil),   // 35: structure.RemoveDepartmentManagerRequest
	(*RemoveDepartmentManagerResponse)(nil),  // 36: structure.RemoveDepartmentManagerResponse
	(*DepartmentManager)(nil),                // 37: structure.DepartmentManager
	(*HealthRequest)(nil),                    // 38: structure.HealthRequest
	(*HealthResponse)(nil),                   // 39: structure.HealthResponse
}
var file_api_proto_structure_proto_depIdxs = []int32{
	14, // 0: structure.GetAllUniversitiesResponse.universities:type_name -> structure.University
	14, // 1: structure.CreateUniversityResponse.university:type_name -> structure.University
	14, // 2: structure.GetUniversityByIDResponse.university:type_name -> structure.University
	14, // 3: structure.GetUniversityByINNResponse.university:type_name -> structure.University
	15, // 4: structure.GetUniversityStructureResponse.structure:type_name -> structure.UniversityStructure
	14, // 5: structure.UpdateUniversityNameResponse.university:type_name -> structure.University
	14, // 6: structure.CreateOrGetUniversityResponse.university:type_name -> structure.University
	14, // 7: structure.UniversityStructure.university:type_name -> structure.University
	16, // 8: structure.UniversityStructure.branches:type_name -> structure.Branch
	17, // 9: structure.Branch.faculties:type_name -> structure.Faculty
	18, // 10: structure.Faculty.groups:type_name -> structure.Group
	16, // 11: structure.UpdateBranchNameResponse.branch:type_name -> structure.Branch
	17, // 12: structure.UpdateFacultyNameResponse.faculty:type_name -> structure.Faculty
	18, // 13: structure.UpdateGroupNameResponse.group:type_name -> structure.Group
	37, // 14: structure.GetAllDepartmentManagersResponse.managers:type_name -> structure.DepartmentManager
	37, // 15: structure.CreateDepartmentManagerResponse.manager:type_name -> structure.DepartmentManager
	0,  // 16: structure.StructureService.GetAllUniversities:input_type -> structure.GetAllUniversitiesRequest
	2,  // 17: structure.StructureService.CreateUniversity:input_type -> structure.CreateUniversityRequest
	4,  // 18: structure.StructureService.GetUniversityByID:input_type -> structure.GetUniversityByIDRequest
	6,  // 19: structure.StructureService.GetUniversityByINN:input_type -> structure.GetUniversityByINNRequest
	8,  // 20: structure.StructureService.GetUniversityStructure:input_type -> structure.GetUniversityStructureRequest
	10, // 21: structure.StructureService.UpdateUniversityName:input_type -> structure.UpdateUniversityNameRequest
	12, // 22: structure.StructureService.CreateOrGetUniversity:input_type -> structure.CreateOrGetUniversityRequest
	19, // 23: structure.StructureService.CreateStructure:input_type -> structure.CreateStructureRequest
	21, // 24: structure.StructureService.ImportExcel:input_type -> structure.ImportExcelRequest
	23, // 25: structure.StructureService.UpdateBranchName:input_type -> structure.UpdateBranchNameRequest
	25, // 26: structure.StructureService.UpdateFacultyName:input_type -> structure.UpdateFacultyNameRequest
	27, // 27: structure.StructureService.UpdateGroupName:input_type -> structure.UpdateGroupNameRequest
	29, // 28: structure.StructureService.LinkGroupToChat:input_type -> structure.LinkGroupToChatRequest
	31, // 29: structure.StructureService.GetAllDepartmentManagers:input_type -> structure.GetAllDepartmentManagersRequest
	33, // 30: structure.StructureService.CreateDepartmentManager:input_type -> structure.CreateDepartmentManagerRequest
	35, // 31: structure.StructureService.RemoveDepartmentManager:input_type -> structure.RemoveDepartmentManagerRequest
	38, // 32: structure.StructureService.Health:input_type -> structure.HealthRequest
	1,  // 33: structure.StructureService.GetAllUniversities:output_type -> structure.GetAllUniversitiesResponse
	3,  // 34: structure.StructureService.CreateUniversity:output_type -> structure.CreateUniversityResponse
	5,  // 35: structure.StructureService.GetUniversityByID:output_type -> structure.GetUniversityByIDResponse
	7,  // 36: structure.StructureService.GetUniversityByINN:output_type -> structure.GetUniversityByINNResponse
	9,  // 37: structure.StructureService.GetUniversityStructure:output_type -> structure.GetUniversityStructureResponse
	11, // 38: structure.StructureService.UpdateUniversityName:output_type -> structure.UpdateUniversityNameResponse
	13, // 39: structure.StructureService.CreateOrGetUniversity:output_type -> structure.CreateOrGetUniversityResponse
	20, // 40: structure.StructureService.CreateStructure:output_type -> structure.CreateStructureResponse
	22, // 41: structure.StructureService.ImportExcel:output_type -> structure.ImportExcelResponse
	24, // 42: structure.StructureService.UpdateBranchName:output_type -> structure.UpdateBranchNameResponse
	26, // 43: structure.StructureService.UpdateFacultyName:output_type -> structure.UpdateFacultyNameResponse
	28, // 44: structure.StructureService.UpdateGroupName:output_type -> structure.UpdateGroupNameResponse
	30, // 45: structure.StructureService.LinkGroupToChat:output_type -> structure.LinkGroupToChatResponse
	32, // 46: structure.StructureService.GetAllDepartmentManagers:output_type -> structure.GetAllDepartmentManagersResponse
	34, // 47: structure.StructureService.CreateDepartmentManager:output_type -> structure.CreateDepartmentManagerResponse
	36, // 48: structure.StructureService.RemoveDepartmentManager:output_type -> structure.RemoveDepartmentManagerResponse
	39, // 49: structure.StructureService.Health:output_type -> structure.HealthResponse
	33, // [33:50] is the sub-list for method output_type
	16, // [16:33] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_structure_proto_init() }
func file_api_proto_structure_proto_init() {
	if File_api_proto_structure_proto != nil {
		return
	}
	file_api_proto_structure_proto_msgTypes[18].OneofWrappers = []any{}
	file_api_proto_structure_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_structure_proto_rawDesc), len(file_api_proto_structure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_structure_proto_goTypes,
		DependencyIndexes: file_api_proto_structure_proto_depIdxs,
		MessageInfos:      file_api_proto_structure_proto_msgTypes,
	}.Build()
	File_api_proto_structure_proto = out.File
	file_api_proto_structure_proto_goTypes = nil
	file_api_proto_structure_proto_depIdxs = nil
}
