// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/structure.proto

package structurepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUniversityByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByIDRequest) Reset() {
	*x = GetUniversityByIDRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByIDRequest) ProtoMessage() {}

func (x *GetUniversityByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{0}
}

func (x *GetUniversityByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUniversityByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByIDResponse) Reset() {
	*x = GetUniversityByIDResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByIDResponse) ProtoMessage() {}

func (x *GetUniversityByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{1}
}

func (x *GetUniversityByIDResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *GetUniversityByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUniversityByINNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inn           string                 `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByINNRequest) Reset() {
	*x = GetUniversityByINNRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByINNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByINNRequest) ProtoMessage() {}

func (x *GetUniversityByINNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByINNRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityByINNRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{2}
}

func (x *GetUniversityByINNRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type GetUniversityByINNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByINNResponse) Reset() {
	*x = GetUniversityByINNResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByINNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByINNResponse) ProtoMessage() {}

func (x *GetUniversityByINNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByINNResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityByINNResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{3}
}

func (x *GetUniversityByINNResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *GetUniversityByINNResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type University struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Inn           string                 `protobuf:"bytes,3,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp           string                 `protobuf:"bytes,4,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Foiv          string                 `protobuf:"bytes,5,opt,name=foiv,proto3" json:"foiv,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *University) Reset() {
	*x = University{}
	mi := &file_api_proto_structure_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *University) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*University) ProtoMessage() {}

func (x *University) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use University.ProtoReflect.Descriptor instead.
func (*University) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{4}
}

func (x *University) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *University) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *University) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *University) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *University) GetFoiv() string {
	if x != nil {
		return x.Foiv
	}
	return ""
}

func (x *University) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *University) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_proto_structure_proto protoreflect.FileDescriptor

const file_api_proto_structure_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/structure.proto\x12\tstructure\"*\n" +
	"\x18GetUniversityByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"h\n" +
	"\x19GetUniversityByIDResponse\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x19GetUniversityByINNRequest\x12\x10\n" +
	"\x03inn\x18\x01 \x01(\tR\x03inn\"i\n" +
	"\x1aGetUniversityByINNResponse\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa6\x01\n" +
	"\n" +
	"University\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03inn\x18\x03 \x01(\tR\x03inn\x12\x10\n" +
	"\x03kpp\x18\x04 \x01(\tR\x03kpp\x12\x12\n" +
	"\x04foiv\x18\x05 \x01(\tR\x04foiv\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt2\xd5\x01\n" +
	"\x10StructureService\x12^\n" +
	"\x11GetUniversityByID\x12#.structure.GetUniversityByIDRequest\x1a$.structure.GetUniversityByIDResponse\x12a\n" +
	"\x12GetUniversityByINN\x12$.structure.GetUniversityByINNRequest\x1a%.structure.GetUniversityByINNResponseB)Z'structure-service/api/proto;structurepbb\x06proto3"

var (
	file_api_proto_structure_proto_rawDescOnce sync.Once
	file_api_proto_structure_proto_rawDescData []byte
)

func file_api_proto_structure_proto_rawDescGZIP() []byte {
	file_api_proto_structure_proto_rawDescOnce.Do(func() {
		file_api_proto_structure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_structure_proto_rawDesc), len(file_api_proto_structure_proto_rawDesc)))
	})
	return file_api_proto_structure_proto_rawDescData
}

var file_api_proto_structure_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_structure_proto_goTypes = []any{
	(*GetUniversityByIDRequest)(nil),   // 0: structure.GetUniversityByIDRequest
	(*GetUniversityByIDResponse)(nil),  // 1: structure.GetUniversityByIDResponse
	(*GetUniversityByINNRequest)(nil),  // 2: structure.GetUniversityByINNRequest
	(*GetUniversityByINNResponse)(nil), // 3: structure.GetUniversityByINNResponse
	(*University)(nil),                 // 4: structure.University
}
var file_api_proto_structure_proto_depIdxs = []int32{
	4, // 0: structure.GetUniversityByIDResponse.university:type_name -> structure.University
	4, // 1: structure.GetUniversityByINNResponse.university:type_name -> structure.University
	0, // 2: structure.StructureService.GetUniversityByID:input_type -> structure.GetUniversityByIDRequest
	2, // 3: structure.StructureService.GetUniversityByINN:input_type -> structure.GetUniversityByINNRequest
	1, // 4: structure.StructureService.GetUniversityByID:output_type -> structure.GetUniversityByIDResponse
	3, // 5: structure.StructureService.GetUniversityByINN:output_type -> structure.GetUniversityByINNResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_structure_proto_init() }
func file_api_proto_structure_proto_init() {
	if File_api_proto_structure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_structure_proto_rawDesc), len(file_api_proto_structure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_structure_proto_goTypes,
		DependencyIndexes: file_api_proto_structure_proto_depIdxs,
		MessageInfos:      file_api_proto_structure_proto_msgTypes,
	}.Build()
	File_api_proto_structure_proto = out.File
	file_api_proto_structure_proto_goTypes = nil
	file_api_proto_structure_proto_depIdxs = nil
}
