// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.3
// source: api/proto/maxbot.proto

package maxbotproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode описывает тип ошибки, возвращаемый сервисом
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED      ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_PHONE    ErrorCode = 1
	ErrorCode_ERROR_CODE_MAX_ID_NOT_FOUND ErrorCode = 2
	ErrorCode_ERROR_CODE_INTERNAL         ErrorCode = 3
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_PHONE",
		2: "ERROR_CODE_MAX_ID_NOT_FOUND",
		3: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":      0,
		"ERROR_CODE_INVALID_PHONE":    1,
		"ERROR_CODE_MAX_ID_NOT_FOUND": 2,
		"ERROR_CODE_INTERNAL":         3,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_maxbot_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_proto_maxbot_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_maxbot_proto_rawDescGZIP(), []int{0}
}

type GetMaxIDByPhoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *GetMaxIDByPhoneRequest) Reset() {
	*x = GetMaxIDByPhoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_maxbot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaxIDByPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxIDByPhoneRequest) ProtoMessage() {}

func (x *GetMaxIDByPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maxbot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxIDByPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetMaxIDByPhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maxbot_proto_rawDescGZIP(), []int{0}
}

func (x *GetMaxIDByPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetMaxIDByPhoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxId     string    `protobuf:"bytes,1,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	ErrorCode ErrorCode `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=maxbot.ErrorCode" json:"error_code,omitempty"`
	Error     string    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetMaxIDByPhoneResponse) Reset() {
	*x = GetMaxIDByPhoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_maxbot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaxIDByPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxIDByPhoneResponse) ProtoMessage() {}

func (x *GetMaxIDByPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maxbot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxIDByPhoneResponse.ProtoReflect.Descriptor instead.
func (*GetMaxIDByPhoneResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maxbot_proto_rawDescGZIP(), []int{1}
}

func (x *GetMaxIDByPhoneResponse) GetMaxId() string {
	if x != nil {
		return x.MaxId
	}
	return ""
}

func (x *GetMaxIDByPhoneResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *GetMaxIDByPhoneResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ValidatePhoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *ValidatePhoneRequest) Reset() {
	*x = ValidatePhoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_maxbot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatePhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePhoneRequest) ProtoMessage() {}

func (x *ValidatePhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maxbot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePhoneRequest.ProtoReflect.Descriptor instead.
func (*ValidatePhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maxbot_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatePhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ValidatePhoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid           bool      `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	NormalizedPhone string    `protobuf:"bytes,2,opt,name=normalized_phone,json=normalizedPhone,proto3" json:"normalized_phone,omitempty"`
	ErrorCode       ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=maxbot.ErrorCode" json:"error_code,omitempty"`
	Error           string    `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ValidatePhoneResponse) Reset() {
	*x = ValidatePhoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_maxbot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatePhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePhoneResponse) ProtoMessage() {}

func (x *ValidatePhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maxbot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePhoneResponse.ProtoReflect.Descriptor instead.
func (*ValidatePhoneResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maxbot_proto_rawDescGZIP(), []int{3}
}

func (x *ValidatePhoneResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidatePhoneResponse) GetNormalizedPhone() string {
	if x != nil {
		return x.NormalizedPhone
	}
	return ""
}

func (x *ValidatePhoneResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ValidatePhoneResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_maxbot_proto protoreflect.FileDescriptor

var file_api_proto_maxbot_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x78, 0x62,
	0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x61, 0x78, 0x62, 0x6f, 0x74,
	0x22, 0x2e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x49, 0x44, 0x42, 0x79, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x22, 0x78, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x49, 0x44, 0x42, 0x79, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6d,
	0x61, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61, 0x78,
	0x49, 0x64, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x78, 0x62, 0x6f, 0x74, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x14, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0xa0, 0x01, 0x0a, 0x15, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x6e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x78, 0x62, 0x6f, 0x74,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x7f, 0x0a, 0x09, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50, 0x48, 0x4f, 0x4e, 0x45,
	0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x4d, 0x41, 0x58, 0x5f, 0x49, 0x44, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x03, 0x32, 0xb1, 0x01, 0x0a,
	0x0d, 0x4d, 0x61, 0x78, 0x42, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x49, 0x44, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x12, 0x1e, 0x2e, 0x6d, 0x61, 0x78, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x78, 0x49, 0x44, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x61, 0x78, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x78, 0x49, 0x44, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x2e, 0x6d, 0x61, 0x78, 0x62, 0x6f, 0x74, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x61, 0x78, 0x62, 0x6f, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x26, 0x5a, 0x24, 0x6d, 0x61, 0x78, 0x62, 0x6f, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6d, 0x61, 0x78,
	0x62, 0x6f, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_maxbot_proto_rawDescOnce sync.Once
	file_api_proto_maxbot_proto_rawDescData = file_api_proto_maxbot_proto_rawDesc
)

func file_api_proto_maxbot_proto_rawDescGZIP() []byte {
	file_api_proto_maxbot_proto_rawDescOnce.Do(func() {
		file_api_proto_maxbot_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_maxbot_proto_rawDescData)
	})
	return file_api_proto_maxbot_proto_rawDescData
}

var file_api_proto_maxbot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_maxbot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_maxbot_proto_goTypes = []interface{}{
	(ErrorCode)(0),                  // 0: maxbot.ErrorCode
	(*GetMaxIDByPhoneRequest)(nil),  // 1: maxbot.GetMaxIDByPhoneRequest
	(*GetMaxIDByPhoneResponse)(nil), // 2: maxbot.GetMaxIDByPhoneResponse
	(*ValidatePhoneRequest)(nil),    // 3: maxbot.ValidatePhoneRequest
	(*ValidatePhoneResponse)(nil),   // 4: maxbot.ValidatePhoneResponse
}
var file_api_proto_maxbot_proto_depIdxs = []int32{
	0, // 0: maxbot.GetMaxIDByPhoneResponse.error_code:type_name -> maxbot.ErrorCode
	0, // 1: maxbot.ValidatePhoneResponse.error_code:type_name -> maxbot.ErrorCode
	1, // 2: maxbot.MaxBotService.GetMaxIDByPhone:input_type -> maxbot.GetMaxIDByPhoneRequest
	3, // 3: maxbot.MaxBotService.ValidatePhone:input_type -> maxbot.ValidatePhoneRequest
	2, // 4: maxbot.MaxBotService.GetMaxIDByPhone:output_type -> maxbot.GetMaxIDByPhoneResponse
	4, // 5: maxbot.MaxBotService.ValidatePhone:output_type -> maxbot.ValidatePhoneResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_maxbot_proto_init() }
func file_api_proto_maxbot_proto_init() {
	if File_api_proto_maxbot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_maxbot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaxIDByPhoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_maxbot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaxIDByPhoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_maxbot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatePhoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_maxbot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatePhoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_maxbot_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_maxbot_proto_goTypes,
		DependencyIndexes: file_api_proto_maxbot_proto_depIdxs,
		EnumInfos:         file_api_proto_maxbot_proto_enumTypes,
		MessageInfos:      file_api_proto_maxbot_proto_msgTypes,
	}.Build()
	File_api_proto_maxbot_proto = out.File
	file_api_proto_maxbot_proto_rawDesc = nil
	file_api_proto_maxbot_proto_goTypes = nil
	file_api_proto_maxbot_proto_depIdxs = nil
}
