// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/employee/employee.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUniversityByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByIDRequest) Reset() {
	*x = GetUniversityByIDRequest{}
	mi := &file_api_proto_employee_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByIDRequest) ProtoMessage() {}

func (x *GetUniversityByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_employee_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_employee_employee_proto_rawDescGZIP(), []int{0}
}

func (x *GetUniversityByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUniversityByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByIDResponse) Reset() {
	*x = GetUniversityByIDResponse{}
	mi := &file_api_proto_employee_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByIDResponse) ProtoMessage() {}

func (x *GetUniversityByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_employee_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_employee_employee_proto_rawDescGZIP(), []int{1}
}

func (x *GetUniversityByIDResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *GetUniversityByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUniversityByINNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inn           string                 `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByINNRequest) Reset() {
	*x = GetUniversityByINNRequest{}
	mi := &file_api_proto_employee_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByINNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByINNRequest) ProtoMessage() {}

func (x *GetUniversityByINNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_employee_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByINNRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityByINNRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_employee_employee_proto_rawDescGZIP(), []int{2}
}

func (x *GetUniversityByINNRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type GetUniversityByINNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByINNResponse) Reset() {
	*x = GetUniversityByINNResponse{}
	mi := &file_api_proto_employee_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByINNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByINNResponse) ProtoMessage() {}

func (x *GetUniversityByINNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_employee_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByINNResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityByINNResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_employee_employee_proto_rawDescGZIP(), []int{3}
}

func (x *GetUniversityByINNResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *GetUniversityByINNResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUniversityByINNAndKPPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inn           string                 `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp           string                 `protobuf:"bytes,2,opt,name=kpp,proto3" json:"kpp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByINNAndKPPRequest) Reset() {
	*x = GetUniversityByINNAndKPPRequest{}
	mi := &file_api_proto_employee_employee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByINNAndKPPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByINNAndKPPRequest) ProtoMessage() {}

func (x *GetUniversityByINNAndKPPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_employee_employee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByINNAndKPPRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityByINNAndKPPRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_employee_employee_proto_rawDescGZIP(), []int{4}
}

func (x *GetUniversityByINNAndKPPRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *GetUniversityByINNAndKPPRequest) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

type GetUniversityByINNAndKPPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByINNAndKPPResponse) Reset() {
	*x = GetUniversityByINNAndKPPResponse{}
	mi := &file_api_proto_employee_employee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByINNAndKPPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByINNAndKPPResponse) ProtoMessage() {}

func (x *GetUniversityByINNAndKPPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_employee_employee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByINNAndKPPResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityByINNAndKPPResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_employee_employee_proto_rawDescGZIP(), []int{5}
}

func (x *GetUniversityByINNAndKPPResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *GetUniversityByINNAndKPPResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type University struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Inn           string                 `protobuf:"bytes,3,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp           string                 `protobuf:"bytes,4,opt,name=kpp,proto3" json:"kpp,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *University) Reset() {
	*x = University{}
	mi := &file_api_proto_employee_employee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *University) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*University) ProtoMessage() {}

func (x *University) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_employee_employee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use University.ProtoReflect.Descriptor instead.
func (*University) Descriptor() ([]byte, []int) {
	return file_api_proto_employee_employee_proto_rawDescGZIP(), []int{6}
}

func (x *University) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *University) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *University) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *University) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *University) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *University) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetEmployeeByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIDRequest) Reset() {
	*x = GetEmployeeByIDRequest{}
	mi := &file_api_proto_employee_employee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIDRequest) ProtoMessage() {}

func (x *GetEmployeeByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_employee_employee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIDRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_employee_employee_proto_rawDescGZIP(), []int{7}
}

func (x *GetEmployeeByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEmployeeByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIDResponse) Reset() {
	*x = GetEmployeeByIDResponse{}
	mi := &file_api_proto_employee_employee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIDResponse) ProtoMessage() {}

func (x *GetEmployeeByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_employee_employee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIDResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_employee_employee_proto_rawDescGZIP(), []int{8}
}

func (x *GetEmployeeByIDResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

func (x *GetEmployeeByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	UniversityId  int64                  `protobuf:"varint,6,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_api_proto_employee_employee_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_employee_employee_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_api_proto_employee_employee_proto_rawDescGZIP(), []int{9}
}

func (x *Employee) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Employee) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Employee) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Employee) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Employee) GetUniversityId() int64 {
	if x != nil {
		return x.UniversityId
	}
	return 0
}

var File_api_proto_employee_employee_proto protoreflect.FileDescriptor

const file_api_proto_employee_employee_proto_rawDesc = "" +
	"\n" +
	"!api/proto/employee/employee.proto\x12\bemployee\"*\n" +
	"\x18GetUniversityByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"g\n" +
	"\x19GetUniversityByIDResponse\x124\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x14.employee.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x19GetUniversityByINNRequest\x12\x10\n" +
	"\x03inn\x18\x01 \x01(\tR\x03inn\"h\n" +
	"\x1aGetUniversityByINNResponse\x124\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x14.employee.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"E\n" +
	"\x1fGetUniversityByINNAndKPPRequest\x12\x10\n" +
	"\x03inn\x18\x01 \x01(\tR\x03inn\x12\x10\n" +
	"\x03kpp\x18\x02 \x01(\tR\x03kpp\"n\n" +
	" GetUniversityByINNAndKPPResponse\x124\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x14.employee.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x92\x01\n" +
	"\n" +
	"University\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03inn\x18\x03 \x01(\tR\x03inn\x12\x10\n" +
	"\x03kpp\x18\x04 \x01(\tR\x03kpp\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"(\n" +
	"\x16GetEmployeeByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"_\n" +
	"\x17GetEmployeeByIDResponse\x12.\n" +
	"\bemployee\x18\x01 \x01(\v2\x12.employee.EmployeeR\bemployee\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa5\x01\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12#\n" +
	"\runiversity_id\x18\x06 \x01(\x03R\funiversityId2\x9b\x03\n" +
	"\x0fEmployeeService\x12\\\n" +
	"\x11GetUniversityByID\x12\".employee.GetUniversityByIDRequest\x1a#.employee.GetUniversityByIDResponse\x12_\n" +
	"\x12GetUniversityByINN\x12#.employee.GetUniversityByINNRequest\x1a$.employee.GetUniversityByINNResponse\x12q\n" +
	"\x18GetUniversityByINNAndKPP\x12).employee.GetUniversityByINNAndKPPRequest\x1a*.employee.GetUniversityByINNAndKPPResponse\x12V\n" +
	"\x0fGetEmployeeByID\x12 .employee.GetEmployeeByIDRequest\x1a!.employee.GetEmployeeByIDResponseB\"Z employee-service/api/proto;protob\x06proto3"

var (
	file_api_proto_employee_employee_proto_rawDescOnce sync.Once
	file_api_proto_employee_employee_proto_rawDescData []byte
)

func file_api_proto_employee_employee_proto_rawDescGZIP() []byte {
	file_api_proto_employee_employee_proto_rawDescOnce.Do(func() {
		file_api_proto_employee_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_employee_employee_proto_rawDesc), len(file_api_proto_employee_employee_proto_rawDesc)))
	})
	return file_api_proto_employee_employee_proto_rawDescData
}

var file_api_proto_employee_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_employee_employee_proto_goTypes = []any{
	(*GetUniversityByIDRequest)(nil),         // 0: employee.GetUniversityByIDRequest
	(*GetUniversityByIDResponse)(nil),        // 1: employee.GetUniversityByIDResponse
	(*GetUniversityByINNRequest)(nil),        // 2: employee.GetUniversityByINNRequest
	(*GetUniversityByINNResponse)(nil),       // 3: employee.GetUniversityByINNResponse
	(*GetUniversityByINNAndKPPRequest)(nil),  // 4: employee.GetUniversityByINNAndKPPRequest
	(*GetUniversityByINNAndKPPResponse)(nil), // 5: employee.GetUniversityByINNAndKPPResponse
	(*University)(nil),                       // 6: employee.University
	(*GetEmployeeByIDRequest)(nil),           // 7: employee.GetEmployeeByIDRequest
	(*GetEmployeeByIDResponse)(nil),          // 8: employee.GetEmployeeByIDResponse
	(*Employee)(nil),                         // 9: employee.Employee
}
var file_api_proto_employee_employee_proto_depIdxs = []int32{
	6, // 0: employee.GetUniversityByIDResponse.university:type_name -> employee.University
	6, // 1: employee.GetUniversityByINNResponse.university:type_name -> employee.University
	6, // 2: employee.GetUniversityByINNAndKPPResponse.university:type_name -> employee.University
	9, // 3: employee.GetEmployeeByIDResponse.employee:type_name -> employee.Employee
	0, // 4: employee.EmployeeService.GetUniversityByID:input_type -> employee.GetUniversityByIDRequest
	2, // 5: employee.EmployeeService.GetUniversityByINN:input_type -> employee.GetUniversityByINNRequest
	4, // 6: employee.EmployeeService.GetUniversityByINNAndKPP:input_type -> employee.GetUniversityByINNAndKPPRequest
	7, // 7: employee.EmployeeService.GetEmployeeByID:input_type -> employee.GetEmployeeByIDRequest
	1, // 8: employee.EmployeeService.GetUniversityByID:output_type -> employee.GetUniversityByIDResponse
	3, // 9: employee.EmployeeService.GetUniversityByINN:output_type -> employee.GetUniversityByINNResponse
	5, // 10: employee.EmployeeService.GetUniversityByINNAndKPP:output_type -> employee.GetUniversityByINNAndKPPResponse
	8, // 11: employee.EmployeeService.GetEmployeeByID:output_type -> employee.GetEmployeeByIDResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_employee_employee_proto_init() }
func file_api_proto_employee_employee_proto_init() {
	if File_api_proto_employee_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_employee_employee_proto_rawDesc), len(file_api_proto_employee_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_employee_employee_proto_goTypes,
		DependencyIndexes: file_api_proto_employee_employee_proto_depIdxs,
		MessageInfos:      file_api_proto_employee_employee_proto_msgTypes,
	}.Build()
	File_api_proto_employee_employee_proto = out.File
	file_api_proto_employee_employee_proto_goTypes = nil
	file_api_proto_employee_employee_proto_depIdxs = nil
}
