// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/administrators/{admin_id}": {
            "delete": {
                "description": "Удаляет администратора из чата. Нельзя удалить последнего администратора (должно быть минимум 2)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "administrators"
                ],
                "summary": "Удалить администратора из чата",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID администратора",
                        "name": "admin_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/chats": {
            "get": {
                "description": "Выполняет поиск чатов по названию с учетом роли пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chats"
                ],
                "summary": "Поиск чатов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поисковый запрос (название чата)",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Лимит результатов (по умолчанию 50, максимум 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение для пагинации",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Роль пользователя (superadmin, admin, user)",
                        "name": "user_role",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID вуза (для фильтрации, если не superadmin)",
                        "name": "university_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ChatListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/chats/all": {
            "get": {
                "description": "Возвращает список всех чатов с пагинацией (с учетом роли пользователя)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chats"
                ],
                "summary": "Получить все чаты",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Лимит результатов (по умолчанию 50, максимум 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение для пагинации",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Роль пользователя (superadmin, admin, user)",
                        "name": "user_role",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID вуза (для фильтрации, если не superadmin)",
                        "name": "university_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ChatListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/chats/{chat_id}/administrators": {
            "post": {
                "description": "Добавляет нового администратора к чату по номеру телефона",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "administrators"
                ],
                "summary": "Добавить администратора к чату",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID чата",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные администратора",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.AddAdministratorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.Administrator"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/chats/{id}": {
            "get": {
                "description": "Возвращает информацию о чате по его ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chats"
                ],
                "summary": "Получить чат по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID чата",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.Chat"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Administrator": {
            "type": "object",
            "properties": {
                "chat_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "max_id": {
                    "description": "MAX_id администратора",
                    "type": "string"
                },
                "phone": {
                    "description": "Номер телефона администратора",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.University": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inn": {
                    "type": "string"
                },
                "kpp": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "http.AddAdministratorRequest": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "phone": {
                    "type": "string",
                    "example": "+79001234567"
                }
            }
        },
        "http.Administrator": {
            "type": "object",
            "properties": {
                "chat_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "max_id": {
                    "description": "MAX_id администратора",
                    "type": "string"
                },
                "phone": {
                    "description": "Номер телефона администратора",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "http.Chat": {
            "type": "object",
            "properties": {
                "administrators": {
                    "description": "Администраторы чата",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Administrator"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "department": {
                    "description": "Подразделение вуза",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "max_chat_id": {
                    "description": "ID чата в MAX",
                    "type": "string"
                },
                "name": {
                    "description": "Название чата",
                    "type": "string"
                },
                "participants_count": {
                    "description": "Количество участников",
                    "type": "integer"
                },
                "source": {
                    "description": "Источник: \"admin_panel\", \"bot_registrar\", \"academic_group\"",
                    "type": "string"
                },
                "university": {
                    "description": "Вуз (для суперадмина)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.University"
                        }
                    ]
                },
                "university_id": {
                    "description": "ID вуза (опционально)",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "description": "Ссылка на чат",
                    "type": "string"
                }
            }
        },
        "http.ChatListResponse": {
            "type": "object",
            "properties": {
                "chats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.Chat"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "http.DeleteResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "deleted"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Chat Service API",
	Description:      "Сервис управления групповыми чатами для мини-приложения",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
