// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/auth.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	api/proto/auth.proto

It has these top-level messages:
	ValidateTokenRequest
	ValidateTokenResponse
	GetUserRequest
	GetUserResponse
	GetUserPermissionsRequest
	GetUserPermissionsResponse
	UserPermission
	CreateUserRequest
	CreateUserResponse
	AssignRoleRequest
	AssignRoleResponse
	RevokeUserRolesRequest
	RevokeUserRolesResponse
	RequestPasswordResetRequest
	RequestPasswordResetResponse
	ResetPasswordRequest
	ResetPasswordResponse
	ChangePasswordRequest
	ChangePasswordResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ValidateTokenRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *ValidateTokenRequest) Reset()                    { *m = ValidateTokenRequest{} }
func (m *ValidateTokenRequest) String() string            { return proto1.CompactTextString(m) }
func (*ValidateTokenRequest) ProtoMessage()               {}
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ValidateTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	Valid        bool   `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	UserId       int64  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Phone        string `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	Role         string `protobuf:"bytes,4,opt,name=role" json:"role,omitempty"`
	UniversityId int64  `protobuf:"varint,5,opt,name=university_id,json=universityId" json:"university_id,omitempty"`
	BranchId     int64  `protobuf:"varint,6,opt,name=branch_id,json=branchId" json:"branch_id,omitempty"`
	FacultyId    int64  `protobuf:"varint,7,opt,name=faculty_id,json=facultyId" json:"faculty_id,omitempty"`
	Error        string `protobuf:"bytes,8,opt,name=error" json:"error,omitempty"`
	Email        string `protobuf:"bytes,9,opt,name=email" json:"email,omitempty"`
}

func (m *ValidateTokenResponse) Reset()                    { *m = ValidateTokenResponse{} }
func (m *ValidateTokenResponse) String() string            { return proto1.CompactTextString(m) }
func (*ValidateTokenResponse) ProtoMessage()               {}
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ValidateTokenResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ValidateTokenResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ValidateTokenResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ValidateTokenResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ValidateTokenResponse) GetUniversityId() int64 {
	if m != nil {
		return m.UniversityId
	}
	return 0
}

func (m *ValidateTokenResponse) GetBranchId() int64 {
	if m != nil {
		return m.BranchId
	}
	return 0
}

func (m *ValidateTokenResponse) GetFacultyId() int64 {
	if m != nil {
		return m.FacultyId
	}
	return 0
}

func (m *ValidateTokenResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ValidateTokenResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserResponse struct {
	Id    int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Phone string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	Role  string `protobuf:"bytes,3,opt,name=role" json:"role,omitempty"`
	Error string `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	Email string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *GetUserResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *GetUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserPermissionsRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *GetUserPermissionsRequest) Reset()                    { *m = GetUserPermissionsRequest{} }
func (m *GetUserPermissionsRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetUserPermissionsRequest) ProtoMessage()               {}
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUserPermissionsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserPermissionsResponse struct {
	Permissions []*UserPermission `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
	Error       string            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetUserPermissionsResponse) Reset()                    { *m = GetUserPermissionsResponse{} }
func (m *GetUserPermissionsResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetUserPermissionsResponse) ProtoMessage()               {}
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetUserPermissionsResponse) GetPermissions() []*UserPermission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *GetUserPermissionsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UserPermission struct {
	Id           int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId       int64  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	RoleId       int64  `protobuf:"varint,3,opt,name=role_id,json=roleId" json:"role_id,omitempty"`
	RoleName     string `protobuf:"bytes,4,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	UniversityId int64  `protobuf:"varint,5,opt,name=university_id,json=universityId" json:"university_id,omitempty"`
	BranchId     int64  `protobuf:"varint,6,opt,name=branch_id,json=branchId" json:"branch_id,omitempty"`
	FacultyId    int64  `protobuf:"varint,7,opt,name=faculty_id,json=facultyId" json:"faculty_id,omitempty"`
}

func (m *UserPermission) Reset()                    { *m = UserPermission{} }
func (m *UserPermission) String() string            { return proto1.CompactTextString(m) }
func (*UserPermission) ProtoMessage()               {}
func (*UserPermission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UserPermission) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserPermission) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserPermission) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *UserPermission) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *UserPermission) GetUniversityId() int64 {
	if m != nil {
		return m.UniversityId
	}
	return 0
}

func (m *UserPermission) GetBranchId() int64 {
	if m != nil {
		return m.BranchId
	}
	return 0
}

func (m *UserPermission) GetFacultyId() int64 {
	if m != nil {
		return m.FacultyId
	}
	return 0
}

type CreateUserRequest struct {
	Phone    string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserResponse struct {
	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto1.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateUserResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AssignRoleRequest struct {
	UserId       int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Role         string `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
	UniversityId int64  `protobuf:"varint,3,opt,name=university_id,json=universityId" json:"university_id,omitempty"`
	BranchId     int64  `protobuf:"varint,4,opt,name=branch_id,json=branchId" json:"branch_id,omitempty"`
	FacultyId    int64  `protobuf:"varint,5,opt,name=faculty_id,json=facultyId" json:"faculty_id,omitempty"`
}

func (m *AssignRoleRequest) Reset()                    { *m = AssignRoleRequest{} }
func (m *AssignRoleRequest) String() string            { return proto1.CompactTextString(m) }
func (*AssignRoleRequest) ProtoMessage()               {}
func (*AssignRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *AssignRoleRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AssignRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *AssignRoleRequest) GetUniversityId() int64 {
	if m != nil {
		return m.UniversityId
	}
	return 0
}

func (m *AssignRoleRequest) GetBranchId() int64 {
	if m != nil {
		return m.BranchId
	}
	return 0
}

func (m *AssignRoleRequest) GetFacultyId() int64 {
	if m != nil {
		return m.FacultyId
	}
	return 0
}

type AssignRoleResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *AssignRoleResponse) Reset()                    { *m = AssignRoleResponse{} }
func (m *AssignRoleResponse) String() string            { return proto1.CompactTextString(m) }
func (*AssignRoleResponse) ProtoMessage()               {}
func (*AssignRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AssignRoleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AssignRoleResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RevokeUserRolesRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *RevokeUserRolesRequest) Reset()                    { *m = RevokeUserRolesRequest{} }
func (m *RevokeUserRolesRequest) String() string            { return proto1.CompactTextString(m) }
func (*RevokeUserRolesRequest) ProtoMessage()               {}
func (*RevokeUserRolesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RevokeUserRolesRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RevokeUserRolesResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *RevokeUserRolesResponse) Reset()                    { *m = RevokeUserRolesResponse{} }
func (m *RevokeUserRolesResponse) String() string            { return proto1.CompactTextString(m) }
func (*RevokeUserRolesResponse) ProtoMessage()               {}
func (*RevokeUserRolesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *RevokeUserRolesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RevokeUserRolesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RequestPasswordResetRequest struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *RequestPasswordResetRequest) Reset()                    { *m = RequestPasswordResetRequest{} }
func (m *RequestPasswordResetRequest) String() string            { return proto1.CompactTextString(m) }
func (*RequestPasswordResetRequest) ProtoMessage()               {}
func (*RequestPasswordResetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *RequestPasswordResetRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type RequestPasswordResetResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *RequestPasswordResetResponse) Reset()                    { *m = RequestPasswordResetResponse{} }
func (m *RequestPasswordResetResponse) String() string            { return proto1.CompactTextString(m) }
func (*RequestPasswordResetResponse) ProtoMessage()               {}
func (*RequestPasswordResetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RequestPasswordResetResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RequestPasswordResetResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResetPasswordRequest struct {
	Token       string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	NewPassword string `protobuf:"bytes,2,opt,name=new_password,json=newPassword" json:"new_password,omitempty"`
}

func (m *ResetPasswordRequest) Reset()                    { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string            { return proto1.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()               {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ResetPasswordResponse) Reset()                    { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string            { return proto1.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()               {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ResetPasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResetPasswordResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ChangePasswordRequest struct {
	UserId          int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	CurrentPassword string `protobuf:"bytes,2,opt,name=current_password,json=currentPassword" json:"current_password,omitempty"`
	NewPassword     string `protobuf:"bytes,3,opt,name=new_password,json=newPassword" json:"new_password,omitempty"`
}

func (m *ChangePasswordRequest) Reset()                    { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string            { return proto1.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()               {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ChangePasswordRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangePasswordRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ChangePasswordResponse) Reset()                    { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string            { return proto1.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()               {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ChangePasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ChangePasswordResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto1.RegisterType((*ValidateTokenRequest)(nil), "auth.ValidateTokenRequest")
	proto1.RegisterType((*ValidateTokenResponse)(nil), "auth.ValidateTokenResponse")
	proto1.RegisterType((*GetUserRequest)(nil), "auth.GetUserRequest")
	proto1.RegisterType((*GetUserResponse)(nil), "auth.GetUserResponse")
	proto1.RegisterType((*GetUserPermissionsRequest)(nil), "auth.GetUserPermissionsRequest")
	proto1.RegisterType((*GetUserPermissionsResponse)(nil), "auth.GetUserPermissionsResponse")
	proto1.RegisterType((*UserPermission)(nil), "auth.UserPermission")
	proto1.RegisterType((*CreateUserRequest)(nil), "auth.CreateUserRequest")
	proto1.RegisterType((*CreateUserResponse)(nil), "auth.CreateUserResponse")
	proto1.RegisterType((*AssignRoleRequest)(nil), "auth.AssignRoleRequest")
	proto1.RegisterType((*AssignRoleResponse)(nil), "auth.AssignRoleResponse")
	proto1.RegisterType((*RevokeUserRolesRequest)(nil), "auth.RevokeUserRolesRequest")
	proto1.RegisterType((*RevokeUserRolesResponse)(nil), "auth.RevokeUserRolesResponse")
	proto1.RegisterType((*RequestPasswordResetRequest)(nil), "auth.RequestPasswordResetRequest")
	proto1.RegisterType((*RequestPasswordResetResponse)(nil), "auth.RequestPasswordResetResponse")
	proto1.RegisterType((*ResetPasswordRequest)(nil), "auth.ResetPasswordRequest")
	proto1.RegisterType((*ResetPasswordResponse)(nil), "auth.ResetPasswordResponse")
	proto1.RegisterType((*ChangePasswordRequest)(nil), "auth.ChangePasswordRequest")
	proto1.RegisterType((*ChangePasswordResponse)(nil), "auth.ChangePasswordResponse")
}

func init() { proto1.RegisterFile("api/proto/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 772 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0x96, 0xe3, 0xa4, 0x49, 0x26, 0x6d, 0xfa, 0x77, 0x95, 0x34, 0xfe, 0xdd, 0x14, 0x52, 0x73,
	0xd3, 0x4a, 0xd0, 0x8a, 0x16, 0x71, 0xc3, 0x05, 0x2a, 0x45, 0x6a, 0x23, 0xa4, 0x52, 0x99, 0x93,
	0x04, 0x42, 0x95, 0x9b, 0x2c, 0x8d, 0x69, 0x62, 0x87, 0x5d, 0x3b, 0x11, 0x37, 0xbc, 0x0b, 0x6f,
	0xc0, 0xa3, 0xf0, 0x42, 0x48, 0x68, 0x0f, 0x3e, 0xdb, 0x89, 0x14, 0x89, 0x9b, 0xd6, 0x33, 0xf3,
	0xcd, 0xe7, 0xd9, 0xd9, 0x6f, 0xc6, 0x81, 0x96, 0x35, 0xb5, 0x8f, 0xa6, 0xc4, 0xf5, 0xdc, 0x23,
	0xcb, 0xf7, 0x46, 0x87, 0xfc, 0x11, 0x95, 0xd9, 0xb3, 0xf1, 0x10, 0x5a, 0xef, 0xad, 0xb1, 0x3d,
	0xb4, 0x3c, 0xfc, 0xd6, 0xbd, 0xc3, 0x8e, 0x89, 0xbf, 0xf9, 0x98, 0x7a, 0xa8, 0x05, 0x15, 0x8f,
	0xd9, 0x9a, 0xd2, 0x53, 0xf6, 0xeb, 0xa6, 0x30, 0x8c, 0x3f, 0x0a, 0xb4, 0x53, 0x70, 0x3a, 0x75,
	0x1d, 0x8a, 0x19, 0x7e, 0xc6, 0x02, 0x1c, 0x5f, 0x33, 0x85, 0x81, 0x3a, 0x50, 0xf5, 0x29, 0x26,
	0xd7, 0xf6, 0x50, 0x2b, 0xf5, 0x94, 0x7d, 0xd5, 0x5c, 0x63, 0x66, 0x7f, 0xc8, 0xe0, 0xd3, 0x91,
	0xeb, 0x60, 0x4d, 0x15, 0xf4, 0xdc, 0x40, 0x08, 0xca, 0xc4, 0x1d, 0x63, 0xad, 0xcc, 0x9d, 0xfc,
	0x19, 0x3d, 0x80, 0x0d, 0xdf, 0xb1, 0x67, 0x98, 0x50, 0xdb, 0xfb, 0xce, 0x88, 0x2a, 0x9c, 0x68,
	0x3d, 0x72, 0xf6, 0x87, 0x68, 0x07, 0xea, 0x37, 0xc4, 0x72, 0x06, 0x23, 0x06, 0x58, 0xe3, 0x80,
	0x9a, 0x70, 0xf4, 0x87, 0x68, 0x17, 0xe0, 0x8b, 0x35, 0xf0, 0xc7, 0x22, 0xbd, 0xca, 0xa3, 0x75,
	0xe9, 0x11, 0xa5, 0x60, 0x42, 0x5c, 0xa2, 0xd5, 0x44, 0x29, 0xdc, 0xe0, 0xde, 0x89, 0x65, 0x8f,
	0xb5, 0xba, 0xf4, 0x32, 0xc3, 0x38, 0x80, 0xe6, 0x39, 0xf6, 0xde, 0x51, 0x4c, 0x82, 0x3e, 0xc5,
	0x4e, 0xa8, 0xc4, 0x4f, 0x68, 0xcc, 0x61, 0x33, 0x84, 0xca, 0x1e, 0x35, 0xa1, 0x14, 0xc2, 0x4a,
	0x76, 0xac, 0x09, 0xa5, 0xbc, 0x26, 0xa8, 0xb1, 0x26, 0x84, 0x35, 0x96, 0x73, 0x6b, 0xac, 0xc4,
	0x6b, 0x7c, 0x02, 0xff, 0xcb, 0x17, 0x5f, 0x61, 0x32, 0xb1, 0x29, 0xb5, 0x5d, 0x87, 0x2e, 0x2d,
	0xf7, 0x2b, 0xe8, 0x79, 0x59, 0xb2, 0xf2, 0xa7, 0xd0, 0x98, 0x46, 0x6e, 0x4d, 0xe9, 0xa9, 0xfb,
	0x8d, 0xe3, 0xd6, 0x21, 0x57, 0x53, 0x32, 0xc7, 0x8c, 0x03, 0xa3, 0xba, 0x4b, 0xb1, 0xba, 0x8d,
	0xdf, 0x0a, 0x34, 0x93, 0x59, 0x99, 0xd6, 0x14, 0x0a, 0xa7, 0x03, 0x55, 0xd6, 0x11, 0x16, 0x50,
	0x45, 0x80, 0x99, 0x42, 0x02, 0x3c, 0xe0, 0x58, 0x93, 0x40, 0x40, 0x35, 0xe6, 0xb8, 0xb4, 0x26,
	0xff, 0x5e, 0x44, 0xc6, 0x27, 0xd8, 0x3a, 0x23, 0xd8, 0xf2, 0x70, 0x5c, 0x1b, 0xe1, 0xfd, 0x2a,
	0xf1, 0xfb, 0xd5, 0xa1, 0x36, 0xb5, 0x28, 0x9d, 0xbb, 0x64, 0x28, 0xdb, 0x12, 0xda, 0xd1, 0x8d,
	0xaa, 0xf1, 0x1b, 0x3d, 0x03, 0x14, 0x27, 0x97, 0x77, 0x52, 0x74, 0x95, 0x05, 0x4d, 0xff, 0xa9,
	0xc0, 0xd6, 0x29, 0xa5, 0xf6, 0xad, 0x63, 0xba, 0x63, 0xbc, 0x4c, 0x0f, 0xa1, 0x0a, 0x4b, 0x8b,
	0x46, 0x51, 0x5d, 0xd6, 0xc5, 0xf2, 0xc2, 0x2e, 0x56, 0xd2, 0x5d, 0x7c, 0x09, 0x28, 0x5e, 0xa2,
	0x3c, 0xa8, 0x06, 0x55, 0xea, 0x0f, 0x06, 0x98, 0x52, 0xb9, 0x5c, 0x02, 0xb3, 0xe0, 0xa4, 0x8f,
	0x61, 0xdb, 0xc4, 0x33, 0xf7, 0x4e, 0xb4, 0xcb, 0x1d, 0xe3, 0xe5, 0xea, 0xef, 0x43, 0x27, 0x93,
	0xb2, 0xe2, 0xdb, 0x4f, 0x60, 0x47, 0xbe, 0xee, 0x4a, 0xde, 0xaa, 0x89, 0x29, 0xf6, 0x16, 0x6a,
	0xc2, 0xb8, 0x84, 0x6e, 0x7e, 0xd2, 0x8a, 0x45, 0xbc, 0x86, 0x16, 0x27, 0x88, 0xd8, 0x16, 0x6c,
	0x75, 0xb4, 0x07, 0xeb, 0x0e, 0x9e, 0x5f, 0xa7, 0x54, 0xd9, 0x70, 0xf0, 0x3c, 0xc8, 0x37, 0xce,
	0xa1, 0x9d, 0x22, 0x5c, 0xb1, 0xb2, 0x1f, 0xd0, 0x3e, 0x1b, 0x59, 0xce, 0x2d, 0x4e, 0x97, 0x56,
	0xa8, 0xc4, 0x03, 0xf8, 0x6f, 0xe0, 0x13, 0x82, 0x1d, 0x2f, 0x5d, 0xe1, 0xa6, 0xf4, 0x07, 0x54,
	0x99, 0x83, 0xa8, 0xd9, 0x83, 0x5c, 0xc0, 0x76, 0xfa, 0xfd, 0xab, 0x9d, 0xe4, 0xf8, 0x57, 0x05,
	0x1a, 0xa7, 0xbe, 0x37, 0x7a, 0x83, 0xc9, 0xcc, 0x1e, 0x60, 0x74, 0x01, 0x1b, 0x89, 0x4f, 0x23,
	0xd2, 0xc5, 0x7e, 0xcc, 0xfb, 0xbc, 0xea, 0x3b, 0xb9, 0xb1, 0x70, 0xdb, 0x56, 0xe5, 0x2e, 0x46,
	0x72, 0xc7, 0x26, 0x3f, 0x3a, 0x7a, 0x3b, 0xe5, 0x95, 0x79, 0x1f, 0x00, 0x65, 0x77, 0x38, 0xba,
	0x9f, 0x00, 0x67, 0xbf, 0x09, 0x7a, 0xaf, 0x18, 0x20, 0x89, 0x9f, 0x03, 0x44, 0x0b, 0x08, 0x75,
	0x04, 0x3e, 0xb3, 0xef, 0x74, 0x2d, 0x1b, 0x88, 0x08, 0xa2, 0xc1, 0x0e, 0x08, 0x32, 0xdb, 0x28,
	0x20, 0xc8, 0xd9, 0x01, 0x97, 0xb0, 0x99, 0x1a, 0x50, 0xd4, 0x15, 0xe0, 0xfc, 0x51, 0xd7, 0x77,
	0x0b, 0xa2, 0x92, 0xef, 0x33, 0x1b, 0x90, 0xec, 0xc0, 0xa1, 0xbd, 0x20, 0xad, 0x70, 0x82, 0x75,
	0x63, 0x11, 0x44, 0xd2, 0x5f, 0xc0, 0x46, 0x62, 0x5c, 0x02, 0x2d, 0xe4, 0x0d, 0x65, 0xa0, 0x85,
	0xfc, 0xf9, 0x7a, 0x05, 0xcd, 0xa4, 0x5e, 0x91, 0x84, 0xe7, 0x4e, 0x91, 0xde, 0xcd, 0x0f, 0x0a,
	0xb2, 0x17, 0xf7, 0x3e, 0x76, 0x59, 0xf8, 0x11, 0x15, 0x92, 0x3d, 0x0a, 0x7f, 0x17, 0x3e, 0xe3,
	0x7f, 0x6f, 0xd6, 0xf8, 0xbf, 0x93, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x3b, 0x46, 0xb3,
	0x31, 0x0a, 0x00, 0x00,
}
