// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/structure.proto

package structurepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUniversityByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByIDRequest) Reset() {
	*x = GetUniversityByIDRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByIDRequest) ProtoMessage() {}

func (x *GetUniversityByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{0}
}

func (x *GetUniversityByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUniversityByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByIDResponse) Reset() {
	*x = GetUniversityByIDResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByIDResponse) ProtoMessage() {}

func (x *GetUniversityByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{1}
}

func (x *GetUniversityByIDResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *GetUniversityByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUniversityByINNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inn           string                 `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByINNRequest) Reset() {
	*x = GetUniversityByINNRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByINNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByINNRequest) ProtoMessage() {}

func (x *GetUniversityByINNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByINNRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityByINNRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{2}
}

func (x *GetUniversityByINNRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type GetUniversityByINNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityByINNResponse) Reset() {
	*x = GetUniversityByINNResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityByINNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityByINNResponse) ProtoMessage() {}

func (x *GetUniversityByINNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityByINNResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityByINNResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{3}
}

func (x *GetUniversityByINNResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *GetUniversityByINNResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateOrGetUniversityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inn           string                 `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp           string                 `protobuf:"bytes,2,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Foiv          string                 `protobuf:"bytes,4,opt,name=foiv,proto3" json:"foiv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrGetUniversityRequest) Reset() {
	*x = CreateOrGetUniversityRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrGetUniversityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrGetUniversityRequest) ProtoMessage() {}

func (x *CreateOrGetUniversityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrGetUniversityRequest.ProtoReflect.Descriptor instead.
func (*CreateOrGetUniversityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrGetUniversityRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *CreateOrGetUniversityRequest) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *CreateOrGetUniversityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrGetUniversityRequest) GetFoiv() string {
	if x != nil {
		return x.Foiv
	}
	return ""
}

type CreateOrGetUniversityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrGetUniversityResponse) Reset() {
	*x = CreateOrGetUniversityResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrGetUniversityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrGetUniversityResponse) ProtoMessage() {}

func (x *CreateOrGetUniversityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrGetUniversityResponse.ProtoReflect.Descriptor instead.
func (*CreateOrGetUniversityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrGetUniversityResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

func (x *CreateOrGetUniversityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type University struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Inn           string                 `protobuf:"bytes,3,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp           string                 `protobuf:"bytes,4,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Foiv          string                 `protobuf:"bytes,5,opt,name=foiv,proto3" json:"foiv,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *University) Reset() {
	*x = University{}
	mi := &file_api_proto_structure_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *University) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*University) ProtoMessage() {}

func (x *University) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use University.ProtoReflect.Descriptor instead.
func (*University) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{6}
}

func (x *University) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *University) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *University) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *University) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *University) GetFoiv() string {
	if x != nil {
		return x.Foiv
	}
	return ""
}

func (x *University) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *University) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateStructureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inn           string                 `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp           string                 `protobuf:"bytes,2,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Foiv          string                 `protobuf:"bytes,3,opt,name=foiv,proto3" json:"foiv,omitempty"`
	OrgName       string                 `protobuf:"bytes,4,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	BranchName    string                 `protobuf:"bytes,5,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	FacultyName   string                 `protobuf:"bytes,6,opt,name=faculty_name,json=facultyName,proto3" json:"faculty_name,omitempty"`
	Course        int32                  `protobuf:"varint,7,opt,name=course,proto3" json:"course,omitempty"`
	GroupNumber   string                 `protobuf:"bytes,8,opt,name=group_number,json=groupNumber,proto3" json:"group_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStructureRequest) Reset() {
	*x = CreateStructureRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStructureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStructureRequest) ProtoMessage() {}

func (x *CreateStructureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStructureRequest.ProtoReflect.Descriptor instead.
func (*CreateStructureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{7}
}

func (x *CreateStructureRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *CreateStructureRequest) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *CreateStructureRequest) GetFoiv() string {
	if x != nil {
		return x.Foiv
	}
	return ""
}

func (x *CreateStructureRequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *CreateStructureRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *CreateStructureRequest) GetFacultyName() string {
	if x != nil {
		return x.FacultyName
	}
	return ""
}

func (x *CreateStructureRequest) GetCourse() int32 {
	if x != nil {
		return x.Course
	}
	return 0
}

func (x *CreateStructureRequest) GetGroupNumber() string {
	if x != nil {
		return x.GroupNumber
	}
	return ""
}

type CreateStructureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniversityId  int64                  `protobuf:"varint,1,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	BranchId      *int64                 `protobuf:"varint,2,opt,name=branch_id,json=branchId,proto3,oneof" json:"branch_id,omitempty"`
	FacultyId     *int64                 `protobuf:"varint,3,opt,name=faculty_id,json=facultyId,proto3,oneof" json:"faculty_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStructureResponse) Reset() {
	*x = CreateStructureResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStructureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStructureResponse) ProtoMessage() {}

func (x *CreateStructureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStructureResponse.ProtoReflect.Descriptor instead.
func (*CreateStructureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{8}
}

func (x *CreateStructureResponse) GetUniversityId() int64 {
	if x != nil {
		return x.UniversityId
	}
	return 0
}

func (x *CreateStructureResponse) GetBranchId() int64 {
	if x != nil && x.BranchId != nil {
		return *x.BranchId
	}
	return 0
}

func (x *CreateStructureResponse) GetFacultyId() int64 {
	if x != nil && x.FacultyId != nil {
		return *x.FacultyId
	}
	return 0
}

func (x *CreateStructureResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateStructureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LinkGroupToChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkGroupToChatRequest) Reset() {
	*x = LinkGroupToChatRequest{}
	mi := &file_api_proto_structure_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkGroupToChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkGroupToChatRequest) ProtoMessage() {}

func (x *LinkGroupToChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkGroupToChatRequest.ProtoReflect.Descriptor instead.
func (*LinkGroupToChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{9}
}

func (x *LinkGroupToChatRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *LinkGroupToChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type LinkGroupToChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkGroupToChatResponse) Reset() {
	*x = LinkGroupToChatResponse{}
	mi := &file_api_proto_structure_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkGroupToChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkGroupToChatResponse) ProtoMessage() {}

func (x *LinkGroupToChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_structure_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkGroupToChatResponse.ProtoReflect.Descriptor instead.
func (*LinkGroupToChatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_structure_proto_rawDescGZIP(), []int{10}
}

func (x *LinkGroupToChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LinkGroupToChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_structure_proto protoreflect.FileDescriptor

const file_api_proto_structure_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/structure.proto\x12\tstructure\"*\n" +
	"\x18GetUniversityByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"h\n" +
	"\x19GetUniversityByIDResponse\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x19GetUniversityByINNRequest\x12\x10\n" +
	"\x03inn\x18\x01 \x01(\tR\x03inn\"i\n" +
	"\x1aGetUniversityByINNResponse\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"j\n" +
	"\x1cCreateOrGetUniversityRequest\x12\x10\n" +
	"\x03inn\x18\x01 \x01(\tR\x03inn\x12\x10\n" +
	"\x03kpp\x18\x02 \x01(\tR\x03kpp\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04foiv\x18\x04 \x01(\tR\x04foiv\"l\n" +
	"\x1dCreateOrGetUniversityResponse\x125\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x15.structure.UniversityR\n" +
	"university\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa6\x01\n" +
	"\n" +
	"University\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03inn\x18\x03 \x01(\tR\x03inn\x12\x10\n" +
	"\x03kpp\x18\x04 \x01(\tR\x03kpp\x12\x12\n" +
	"\x04foiv\x18\x05 \x01(\tR\x04foiv\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xea\x01\n" +
	"\x16CreateStructureRequest\x12\x10\n" +
	"\x03inn\x18\x01 \x01(\tR\x03inn\x12\x10\n" +
	"\x03kpp\x18\x02 \x01(\tR\x03kpp\x12\x12\n" +
	"\x04foiv\x18\x03 \x01(\tR\x04foiv\x12\x19\n" +
	"\borg_name\x18\x04 \x01(\tR\aorgName\x12\x1f\n" +
	"\vbranch_name\x18\x05 \x01(\tR\n" +
	"branchName\x12!\n" +
	"\ffaculty_name\x18\x06 \x01(\tR\vfacultyName\x12\x16\n" +
	"\x06course\x18\a \x01(\x05R\x06course\x12!\n" +
	"\fgroup_number\x18\b \x01(\tR\vgroupNumber\"\xd2\x01\n" +
	"\x17CreateStructureResponse\x12#\n" +
	"\runiversity_id\x18\x01 \x01(\x03R\funiversityId\x12 \n" +
	"\tbranch_id\x18\x02 \x01(\x03H\x00R\bbranchId\x88\x01\x01\x12\"\n" +
	"\n" +
	"faculty_id\x18\x03 \x01(\x03H\x01R\tfacultyId\x88\x01\x01\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\x03R\agroupId\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorB\f\n" +
	"\n" +
	"_branch_idB\r\n" +
	"\v_faculty_id\"L\n" +
	"\x16LinkGroupToChatRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\"I\n" +
	"\x17LinkGroupToChatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xf5\x03\n" +
	"\x10StructureService\x12^\n" +
	"\x11GetUniversityByID\x12#.structure.GetUniversityByIDRequest\x1a$.structure.GetUniversityByIDResponse\x12a\n" +
	"\x12GetUniversityByINN\x12$.structure.GetUniversityByINNRequest\x1a%.structure.GetUniversityByINNResponse\x12j\n" +
	"\x15CreateOrGetUniversity\x12'.structure.CreateOrGetUniversityRequest\x1a(.structure.CreateOrGetUniversityResponse\x12X\n" +
	"\x0fCreateStructure\x12!.structure.CreateStructureRequest\x1a\".structure.CreateStructureResponse\x12X\n" +
	"\x0fLinkGroupToChat\x12!.structure.LinkGroupToChatRequest\x1a\".structure.LinkGroupToChatResponseB)Z'structure-service/api/proto;structurepbb\x06proto3"

var (
	file_api_proto_structure_proto_rawDescOnce sync.Once
	file_api_proto_structure_proto_rawDescData []byte
)

func file_api_proto_structure_proto_rawDescGZIP() []byte {
	file_api_proto_structure_proto_rawDescOnce.Do(func() {
		file_api_proto_structure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_structure_proto_rawDesc), len(file_api_proto_structure_proto_rawDesc)))
	})
	return file_api_proto_structure_proto_rawDescData
}

var file_api_proto_structure_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_structure_proto_goTypes = []any{
	(*GetUniversityByIDRequest)(nil),      // 0: structure.GetUniversityByIDRequest
	(*GetUniversityByIDResponse)(nil),     // 1: structure.GetUniversityByIDResponse
	(*GetUniversityByINNRequest)(nil),     // 2: structure.GetUniversityByINNRequest
	(*GetUniversityByINNResponse)(nil),    // 3: structure.GetUniversityByINNResponse
	(*CreateOrGetUniversityRequest)(nil),  // 4: structure.CreateOrGetUniversityRequest
	(*CreateOrGetUniversityResponse)(nil), // 5: structure.CreateOrGetUniversityResponse
	(*University)(nil),                    // 6: structure.University
	(*CreateStructureRequest)(nil),        // 7: structure.CreateStructureRequest
	(*CreateStructureResponse)(nil),       // 8: structure.CreateStructureResponse
	(*LinkGroupToChatRequest)(nil),        // 9: structure.LinkGroupToChatRequest
	(*LinkGroupToChatResponse)(nil),       // 10: structure.LinkGroupToChatResponse
}
var file_api_proto_structure_proto_depIdxs = []int32{
	6,  // 0: structure.GetUniversityByIDResponse.university:type_name -> structure.University
	6,  // 1: structure.GetUniversityByINNResponse.university:type_name -> structure.University
	6,  // 2: structure.CreateOrGetUniversityResponse.university:type_name -> structure.University
	0,  // 3: structure.StructureService.GetUniversityByID:input_type -> structure.GetUniversityByIDRequest
	2,  // 4: structure.StructureService.GetUniversityByINN:input_type -> structure.GetUniversityByINNRequest
	4,  // 5: structure.StructureService.CreateOrGetUniversity:input_type -> structure.CreateOrGetUniversityRequest
	7,  // 6: structure.StructureService.CreateStructure:input_type -> structure.CreateStructureRequest
	9,  // 7: structure.StructureService.LinkGroupToChat:input_type -> structure.LinkGroupToChatRequest
	1,  // 8: structure.StructureService.GetUniversityByID:output_type -> structure.GetUniversityByIDResponse
	3,  // 9: structure.StructureService.GetUniversityByINN:output_type -> structure.GetUniversityByINNResponse
	5,  // 10: structure.StructureService.CreateOrGetUniversity:output_type -> structure.CreateOrGetUniversityResponse
	8,  // 11: structure.StructureService.CreateStructure:output_type -> structure.CreateStructureResponse
	10, // 12: structure.StructureService.LinkGroupToChat:output_type -> structure.LinkGroupToChatResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_structure_proto_init() }
func file_api_proto_structure_proto_init() {
	if File_api_proto_structure_proto != nil {
		return
	}
	file_api_proto_structure_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_structure_proto_rawDesc), len(file_api_proto_structure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_structure_proto_goTypes,
		DependencyIndexes: file_api_proto_structure_proto_depIdxs,
		MessageInfos:      file_api_proto_structure_proto_msgTypes,
	}.Build()
	File_api_proto_structure_proto = out.File
	file_api_proto_structure_proto_goTypes = nil
	file_api_proto_structure_proto_depIdxs = nil
}
