// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/proto/employee.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmployeeService_GetUniversityByID_FullMethodName        = "/employee.EmployeeService/GetUniversityByID"
	EmployeeService_GetUniversityByINN_FullMethodName       = "/employee.EmployeeService/GetUniversityByINN"
	EmployeeService_GetUniversityByINNAndKPP_FullMethodName = "/employee.EmployeeService/GetUniversityByINNAndKPP"
	EmployeeService_GetEmployeeByID_FullMethodName          = "/employee.EmployeeService/GetEmployeeByID"
)

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmployeeService предоставляет методы для работы с сотрудниками и университетами
type EmployeeServiceClient interface {
	// GetUniversityByID получает вуз по ID
	GetUniversityByID(ctx context.Context, in *GetUniversityByIDRequest, opts ...grpc.CallOption) (*GetUniversityByIDResponse, error)
	// GetUniversityByINN получает вуз по ИНН
	GetUniversityByINN(ctx context.Context, in *GetUniversityByINNRequest, opts ...grpc.CallOption) (*GetUniversityByINNResponse, error)
	// GetUniversityByINNAndKPP получает вуз по ИНН и КПП
	GetUniversityByINNAndKPP(ctx context.Context, in *GetUniversityByINNAndKPPRequest, opts ...grpc.CallOption) (*GetUniversityByINNAndKPPResponse, error)
	// GetEmployeeByID получает сотрудника по ID
	GetEmployeeByID(ctx context.Context, in *GetEmployeeByIDRequest, opts ...grpc.CallOption) (*GetEmployeeByIDResponse, error)
}

type employeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeServiceClient(cc grpc.ClientConnInterface) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetUniversityByID(ctx context.Context, in *GetUniversityByIDRequest, opts ...grpc.CallOption) (*GetUniversityByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUniversityByIDResponse)
	err := c.cc.Invoke(ctx, EmployeeService_GetUniversityByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetUniversityByINN(ctx context.Context, in *GetUniversityByINNRequest, opts ...grpc.CallOption) (*GetUniversityByINNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUniversityByINNResponse)
	err := c.cc.Invoke(ctx, EmployeeService_GetUniversityByINN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetUniversityByINNAndKPP(ctx context.Context, in *GetUniversityByINNAndKPPRequest, opts ...grpc.CallOption) (*GetUniversityByINNAndKPPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUniversityByINNAndKPPResponse)
	err := c.cc.Invoke(ctx, EmployeeService_GetUniversityByINNAndKPP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetEmployeeByID(ctx context.Context, in *GetEmployeeByIDRequest, opts ...grpc.CallOption) (*GetEmployeeByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeByIDResponse)
	err := c.cc.Invoke(ctx, EmployeeService_GetEmployeeByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
// All implementations must embed UnimplementedEmployeeServiceServer
// for forward compatibility.
//
// EmployeeService предоставляет методы для работы с сотрудниками и университетами
type EmployeeServiceServer interface {
	// GetUniversityByID получает вуз по ID
	GetUniversityByID(context.Context, *GetUniversityByIDRequest) (*GetUniversityByIDResponse, error)
	// GetUniversityByINN получает вуз по ИНН
	GetUniversityByINN(context.Context, *GetUniversityByINNRequest) (*GetUniversityByINNResponse, error)
	// GetUniversityByINNAndKPP получает вуз по ИНН и КПП
	GetUniversityByINNAndKPP(context.Context, *GetUniversityByINNAndKPPRequest) (*GetUniversityByINNAndKPPResponse, error)
	// GetEmployeeByID получает сотрудника по ID
	GetEmployeeByID(context.Context, *GetEmployeeByIDRequest) (*GetEmployeeByIDResponse, error)
	mustEmbedUnimplementedEmployeeServiceServer()
}

// UnimplementedEmployeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmployeeServiceServer struct{}

func (UnimplementedEmployeeServiceServer) GetUniversityByID(context.Context, *GetUniversityByIDRequest) (*GetUniversityByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniversityByID not implemented")
}
func (UnimplementedEmployeeServiceServer) GetUniversityByINN(context.Context, *GetUniversityByINNRequest) (*GetUniversityByINNResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniversityByINN not implemented")
}
func (UnimplementedEmployeeServiceServer) GetUniversityByINNAndKPP(context.Context, *GetUniversityByINNAndKPPRequest) (*GetUniversityByINNAndKPPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniversityByINNAndKPP not implemented")
}
func (UnimplementedEmployeeServiceServer) GetEmployeeByID(context.Context, *GetEmployeeByIDRequest) (*GetEmployeeByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmployeeByID not implemented")
}
func (UnimplementedEmployeeServiceServer) mustEmbedUnimplementedEmployeeServiceServer() {}
func (UnimplementedEmployeeServiceServer) testEmbeddedByValue()                         {}

// UnsafeEmployeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeServiceServer will
// result in compilation errors.
type UnsafeEmployeeServiceServer interface {
	mustEmbedUnimplementedEmployeeServiceServer()
}

func RegisterEmployeeServiceServer(s grpc.ServiceRegistrar, srv EmployeeServiceServer) {
	// If the following call panics, it indicates UnimplementedEmployeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmployeeService_ServiceDesc, srv)
}

func _EmployeeService_GetUniversityByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUniversityByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetUniversityByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeService_GetUniversityByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetUniversityByID(ctx, req.(*GetUniversityByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetUniversityByINN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUniversityByINNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetUniversityByINN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeService_GetUniversityByINN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetUniversityByINN(ctx, req.(*GetUniversityByINNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetUniversityByINNAndKPP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUniversityByINNAndKPPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetUniversityByINNAndKPP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeService_GetUniversityByINNAndKPP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetUniversityByINNAndKPP(ctx, req.(*GetUniversityByINNAndKPPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetEmployeeByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetEmployeeByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeService_GetEmployeeByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetEmployeeByID(ctx, req.(*GetEmployeeByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeService_ServiceDesc is the grpc.ServiceDesc for EmployeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employee.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUniversityByID",
			Handler:    _EmployeeService_GetUniversityByID_Handler,
		},
		{
			MethodName: "GetUniversityByINN",
			Handler:    _EmployeeService_GetUniversityByINN_Handler,
		},
		{
			MethodName: "GetUniversityByINNAndKPP",
			Handler:    _EmployeeService_GetUniversityByINNAndKPP_Handler,
		},
		{
			MethodName: "GetEmployeeByID",
			Handler:    _EmployeeService_GetEmployeeByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/employee.proto",
}
